### ISSUE TITLE
captains-log code analysis // format_stardate

### ISSUE THREAD

**Issue by moviedo** [exercism/elixir#1011]
I think there might be some issue with the code analysis. I get this code recommendation but I'm not sure why.

Recommendation 
```
Use :rand.uniform instead of Enum.random in the format_stardate function. :rand.uniform allows you to generate a random float directly.
```

Code
```
defmodule CaptainsLog do
    @planetary_classes ["D", "H", "J", "K", "L", "M", "N", "R", "T", "Y"]
  
    def random_planet_class() do
      Enum.random(@planetary_classes)
    end
  
    def random_ship_registry_number() do
      "NCC-#{Enum.random(1000..9999)}"
    end
  
    @start 41000.0
    @finish 42000.0
    def random_stardate() do
      :random.uniform() * (@finish - @start) + @start
    end
  
    def format_stardate(stardate) do
      :rand.uniform()
      List.to_string(:io_lib.format("~*.*f", [7, 1, stardate]))
    end
end
 ```
 
`Enum.random` is not used in format_stardate. Used in other parts of the code, maybe this message is meant for a different method?
<img width="442" alt="Screen Shot 2021-11-19 at 21 35 24" src="https://user-images.githubusercontent.com/1228801/142711604-870a970b-3e6e-42f3-bb7a-ba7556ced080.png">

**Comment by angelikatyborska** [comment]
There are two problems here:

1. The comment mentions the wrong function - it was supposed to say:
    > Use `:rand.uniform` instead of `Enum.random` in the `random_stardate` function.

2. The analyzer check looks for the usage of `:rand.uniform` in `random_stardate`. If it doesn't find it, it returns this comment, and the comment makes the assumption that if somebody didn't use `:rand.uniform`, that means they used `Enum.random`. You used `:random.uniform` which makes the comment not accurate 😇 . The `:random` module is deprecated and shouldn't be used at all.

We should probably add a global check about not using the deprecated `:random` module 🤔

**Comment by moviedo** [comment]
@angelikatyborska 
In one of my solution iterations I had the following:

```
  def random_stardate() do
    Enum.random(41000..41999) + :rand.uniform()
  end
```

I still had the above code improvement message.

**Comment by angelikatyborska** [comment]
Right! I just checked again. Indeed there are two checks - one to assert that you do use `:rand.uniform` in `random_stardate`, and one to assert that you do not use `Enum.random` in `random_stardate`. They both produce the same comment.
