### ISSUE TITLE
rpn-calculator // instructions.md // grammar

### ISSUE THREAD

**Issue by moviedo** [exercism/elixir#1012]
I think there is a grammar error with the `Pass on the message` task. I think it's missing a pause, because the sentence seems like a runoff sentence. 

Check the following sentence.
Some of the errors contain important information that your coworkers `need to have to` ensure the correct operation of the system.

I think maybe it should just be: `Some of the errors contain important information that your coworkers need, to ensure the correct operation of the system.`

This correction also makes sense to me: `Some of the errors contain important information that your coworkers need to have, to ensure the correct operation of the system.`

**Comment by jiegillet** [comment]
Thanks for bringing this up.

I actually think the original is better in this case, it is a fairly long sentence but the comma takes the focus away from the reason why the information is important.

I'll let other people weigh in though.

**Comment by angelikatyborska** [comment]
I'm pretty certain the current sentence is correct. It uses a "to + infinite" grammar structure to convey somebody's intention or goal (see "Infinitive of purpose" at https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/to-infinitives). You cannot put a comma before that structure.
