### ISSUE TITLE
 Exercise Recommendations for a Novice Programmer

### ISSUE THREAD

**Issue by 2FO** [exercism/elixir#1016]
Elixir is my first programming language.  I have a basic understanding of the fundamentals (data types, functions, pattern matching etc) but little practice, beyond following tutorials. 

My goal is to build CRUD apps with Phoenix, Postgres and possibly liveview. Apps along the lines of rottentomatoes, twitter etc.
   
I'm assuming that certain exercises would serve as more useful prep than others for building the type of apps I have in mind.  So, I'd be grateful for any input into which ones those might be.

Thanks for stopping by

**Comment by angelikatyborska** [comment]
Hi! The goal of Exercism is to make you fluent in a chosen programming language. All of the exercises are pretty good for that. I would recommend first working through the learning exercises, and then choosing a few easy, medium, and hard practice exercises (don't just focus on the easy ones).

However, none of them have anything to do with writing CRUD apps and won't prepare you for working with the technologies you've mentioned. Exercism isn't just meant for that.

**Comment by 2FO** [comment]
Thanks for the quick reply @angelikatyborska  that's very helpful to know.
