### ISSUE TITLE
Race condition in `Take-A-Number`

### ISSUE THREAD

**Issue by b3k** [exercism/elixir#1021]
Hi,

There is a problem with `Take-A-Number` exercise, in my opinion cased by async nature of erlang processes.

Here is my code:
```elixir
defmodule TakeANumber do
  def start() do
    spawn(fn -> loop(0) end)
  end

  def loop(state) do
    IO.inspect("INIT INBOX: #{Keyword.get(Process.info(self()), :message_queue_len)}")
    receive do
      {:report_state, sender_pid} ->
        IO.inspect("report_state INBOX: #{Keyword.get(Process.info(self()), :message_queue_len)}")
        send(sender_pid, state)
        loop(state)
      {:take_a_number, sender_pid} ->
        IO.inspect("take_a_number INBOX: #{Keyword.get(Process.info(self()), :message_queue_len)}")
        send(sender_pid, state+1)
        loop(state+1)
      :stop ->
        nil
      _ ->
        IO.inspect("DEFAULT INBOX: #{Keyword.get(Process.info(self()), :message_queue_len)}")
        loop(state)
    end
  end
end
```

output of `mix test test/take_a_number_test.exs:75` vary depending on how quick process information of messages queue will be flushed it may be like this:
```
  * test ignores unexpected messages and keeps working [L#75]"INIT INBOX: 3"
"DEFAULT INBOX: 2"
"INIT INBOX: 2"
"DEFAULT INBOX: 1"
"INIT INBOX: 1"
"take_a_number INBOX: 0"
"INIT INBOX: 0"
"report_state INBOX: 0"
"INIT INBOX: 0"
  * test ignores unexpected messages and keeps working (2.7ms) [L#75]

  1) test ignores unexpected messages and keeps working (TakeANumberTest)
     test/take_a_number_test.exs:75
     Assertion with == failed
     code:  assert Keyword.get(Process.info(pid), :message_queue_len) == 0
     left:  1
     right: 0
     stacktrace:
       test/take_a_number_test.exs:87: (test)



Finished in 0.08 seconds (0.00s async, 0.08s sync)
7 tests, 1 failure, 6 excluded

Randomized with seed 0
```

or this:

```
  * test ignores unexpected messages and keeps working [L#75]"INIT INBOX: 3"
"DEFAULT INBOX: 2"
"INIT INBOX: 2"
"DEFAULT INBOX: 1"
"INIT INBOX: 1"
"take_a_number INBOX: 0"
"INIT INBOX: 0"
"report_state INBOX: 0"
"INIT INBOX: 0"
  * test ignores unexpected messages and keeps working (0.6ms) [L#75]


Finished in 0.08 seconds (0.00s async, 0.08s sync)
7 tests, 0 failures, 6 excluded

Randomized with seed 0
```

Using exercise online editor gives almost always error. 

Not sure about the proper solution but, putting small `:timer.sleep(100)` just before `assert Keyword.get(Process.info(pid), :message_queue_len) == 0` makes test working as expected every time.

```elixir
  @tag task_id: 5
  test "ignores unexpected messages and keeps working" do
    pid = TakeANumber.start()

    send(pid, :hello?)
    send(pid, "I want to speak with the manager")

    send(pid, {:take_a_number, self()})
    assert_receive 1

    send(pid, {:report_state, self()})
    assert_receive 1
    :timer.sleep(100)
    assert Keyword.get(Process.info(pid), :message_queue_len) == 0
  end
```

Thanks!

**Comment by angelikatyborska** [comment]
Thank you for reporting!

I cannot reproduce this locally. In the editor, I can only reproduce it when using your code with all the `IO.inspect` calls. As soon as I remove them, the test passes again 🤷.

I think the best course of action is to just remove the last assertion that uses `Process.info`. The docs say about this function: "Use this only for debugging information", which means it was a mistake to rely on it in the first place. Removing it won't break the essence of the test - it will still assert that the process keeps working after unexpected messages.

@b3k Would you like to open a PR with that small change?

**Comment by angelikatyborska** [comment]
Hmm, after 5 more minutes of thinking, I realized that removing this assertion will make a difference. It's the only thing that checks if a catch-all `_` case was used in the `receive` expression. However, I stand by my conclusion and I think we should just add an analyzer check for this case since we cannot have a non-flaky test for it.

In theory changing `== 0` to `< 2` would help with the flakiness, but it would just feel like a hack on top of a hack to me...
