### ISSUE TITLE
Rational numbers: reduce absolute value

### ISSUE THREAD

**Issue by mstranger** [exercism/elixir#1052]
Current tests do not consider the case, when a rational number can be reduced:
```elixir
RationalNumbers.abs({2, 4}) = {2, 4}
```
Should the function `abs` in this exercise reduce a rational number?

**Comment by jiegillet** [comment]
Hi @mstranger,
That's an excellent question! Yes, every function should reduce the output number.
The best place to make that explicit however, is on the problem-specifications repo, [like this recent PR for the same exercise](
https://github.com/exercism/problem-specifications/pull/1914). In this way, every track would benefit from the change. 

Would you be willing to open a PR there?
It would be great to have a test that makes sure that the output is reduced for every function.

**Comment by mstranger** [comment]
Thanks @jiegillet, I created a PR.

**Comment by jiegillet** [comment]
Nice, thank you! 
I'll close the issue, please open a PR here with the new tests once that PR is merged :)
