### ISSUE TITLE
awkward wording in instructions for log-level learning exercise

### ISSUE THREAD

**Issue by glennj** [exercism/elixir#1053]
> If the log label is unknown and it comes from a legacy system, send the alert to the dev1 team, otherwise send it to the dev2 team. All other log labels can be safely ignored.

It's not very clear that "otherwise" belongs to just "it comes from a legacy system". I initially interpreted it as
```elixir
  def alert_recipient(level, legacy?) do
    label = to_label(level, legacy?)
    cond do
      label === :error or label === :fatal -> :ops
      label === :unknown and legacy? -> :dev1
      true -> :dev2
    end
  end
```

Perhaps a bit less punctuation:
> If the log label is unknown, then if it comes from a legacy system send the alert to the dev1 team otherwise send it to the dev2 team. All other log labels can be safely ignored.

Or more punctuation:
>  If the log label is unknown: if it comes from a legacy system, send the alert to the dev1 team; otherwise send it to the dev2 team. All other log labels can be safely ignored.

**Comment by jiegillet** [comment]
I feel playing with punctuation might be too subtle, how about a bit of repetition?

> If you receive a log with an unknown label from a legacy system, send the alert to the dev1 team, other unknown labels should go to the dev2 team, and all other log labels can be safely ignored.

**Comment by angelikatyborska** [comment]
Thank you for the feedback! I like @jiegillet's suggestion. I made a PR.
