### ISSUE TITLE
Booleans | Pacman Rules

### ISSUE THREAD

**Issue by vovs03** [exercism/elixir#1057]
# How is it possible?

> The code of `def win?` output `(true, true, true)` but `test#12` was FAILED.

[test/rules_test.exs:66](https://github.com/exercism/elixir/blob/877030cc795a0f7dedb12390f1cc5a9b79096140/exercises/concept/pacman-rules/test/rules_test.exs#L66)

```Elixir

  def win?(has_eaten_all_dots, power_pellet_active, touching_ghost) do
    # Please implement the win?/3 function

    IO.inspect(has_eaten_all_dots)
    IO.inspect(power_pellet_active)
    IO.inspect(touching_ghost)

   # ...

  end
```

![Screenshot_2022-02-03_02-13-52](https://user-images.githubusercontent.com/21124057/152253642-639c2f59-195a-4082-950e-bf129c298efb.png)

**Comment by jiegillet** [comment]
Could you share the full code of `win?` as well? All I see from what you shared is that all inputs are `true`, but you need to implement the logic to return a single `true`.
