### ISSUE TITLE
Nucleotide Count: Missing Test for "Invalid nucleotide in strand"

### ISSUE THREAD

**Issue by That-David-Guy** [exercism/elixir#1066]
I'm going through the Elixir track, which is fantastic!, and found that the **nucleotide-count** description talks about an error case, but none of the unit tests test for an error case.

Looking at the canonical data it looks like there should be a test (line 68)
- https://github.com/exercism/problem-specifications/blob/main/exercises/nucleotide-count/canonical-data.json

I'm happy to try and create a PR that includes this test if you want?

What would be the best way to handle the error? 

If it's invalid should it `raise "Invalid nucleotide in strand"`?

My assumption for why it's `raise` and not `{:error, msg}` is because when it's valid it's just `value` and not `{:ok, value}`

**Comment by angelikatyborska** [comment]
Hi :)

> I'm going through the Elixir track, which is fantastic

Thank you!

> Looking at the canonical data it looks like there should be a test (line 68)

Indeed, we purposefully chose not to implement that test. You can see that in the [`tests.toml` file](https://github.com/exercism/elixir/blob/8a65c61916257fef33d31226bbc265cf31cb4aae/exercises/practice/nucleotide-count/.meta/tests.toml#L17-L20) of that exercise. We also left a [`design.md` file](https://github.com/exercism/elixir/blob/1c2f9e9465dad026d6f16c260f87948c739ce91c/exercises/practice/nucleotide-count/.meta/design.md) with an explanation. Nothing changed with regard to this reasoning, so we don't want to add that test now. However...

> found that the nucleotide-count description talks about an error case

That is a problem. The description also comes from problem specs, so we cannot change. What we can do is add an `instructions.append.md` file that mentions this discrepancy. I would suggest something like:

```
# Instructions append

## Elixir-specific changes

Error handling has been omitted from this exercise for the sake of simplicity.
```

PS:

> My assumption for why it's raise and not `{:error, msg}` is because when it's valid it's just value and not `{:ok, value}`

If we were adding error handling to an existing exercise, we should prioritize idiomatic Elixir over keeping the changes to minimum, so in that case we would need to change all happy-path return values to `{:ok, value}` and return errors as `{:error, msg}`.

**Comment by That-David-Guy** [comment]
Thanks for the reply. That makes sense.

Does that mean I should create a PR with `instructions.append.md` like you suggested? I'm happy to do this 😀

**Comment by angelikatyborska** [comment]
@That-David-Guy Yes please!
