### ISSUE TITLE
Library Fees Tests 25 & 26 are one day off

### ISSUE THREAD

**Issue by jnnks** [exercism/elixir#1096]
https://github.com/exercism/elixir/blob/c82ea9b2f35b083f2463a04494ee4dc2a47a6185/exercises/concept/library-fees/test/library_fees_test.exs#L150-L160

All tests are successful, except the last two, which are exactly one day off.
Changing the function to accommodate the offset makes other tests fail.
Even previous solutions now seem to fail.

What am I missing here?

**Comment by jnnks** [comment]
Hm, there are two test cases that check that as well, but maybe I manage to get past those :)

<details>
 <summary>My Solution</summary>

```elixir
defmodule LibraryFees do
  def datetime_from_string(string) do
    {:ok, date} = NaiveDateTime.from_iso8601(string)
    date
  end

  def before_noon?(datetime), do: datetime.hour < 12
  def monday?(datetime), do: Date.day_of_week(datetime) == 1

  def return_date(checkout_datetime) do
    add_days = if before_noon?(checkout_datetime), do: 28, else: 29
    checkout_datetime |> NaiveDateTime.add(add_days * 24 * 3600, :second) |> NaiveDateTime.to_date()
  end

  def days_late(planned_return_date, actual_return_datetime) do
    {:ok, rdate} = NaiveDateTime.new(planned_return_date, ~T[12:00:00])

    case NaiveDateTime.compare(rdate, actual_return_datetime) do
      :lt -> diff_in_s = NaiveDateTime.diff(rdate, actual_return_datetime, :second)
             trunc((diff_in_s / (3600 * 24))) * -1
      _ -> 0
    end
  end

  # NOTE: last two test cases seem to be buggy
  #def calculate_late_fee("2021-01-01T08:00:00Z", "2021-02-13T08:00:00Z", 111) do
  #  1665
  #end
  #def calculate_late_fee("2021-01-01T08:00:00Z", "2021-02-15T08:00:00Z", 111) do
  #  943
  #end
  def calculate_late_fee(checkout, return, rate) do
    cd = datetime_from_string(checkout)
    rd = datetime_from_string(return)
    
    dlate = cd |> return_date() |> days_late(rd)
    IO.inspect([cd, rd, dlate])
    
    rate = if monday?(rd), do: rate * 0.5, else: rate
    
    floor(dlate * rate)
  end
end
```

</details>

**Comment by glennj** [comment]
The problem lies in comparing NaiveDateTimes to Dates. in `days_late` for the first failed test, the difference in _float_ number of days -- `14.833333333333334` and when you `trunc()` that, you get 14.

The 4 hours between 08:00:00 and 12:00:00 accounts for the missing 0.1666... days.

Convert the date parameters to Date and use `Date.add/2`

**Comment by jnnks** [comment]
Ah, I see. Thanks for the info.

Could you add another test to catch that rounding error or do you accept pull requests on here?

**Comment by glennj** [comment]
It seems those tests already exist.

**Comment by angelikatyborska** [comment]
Technically @glennj is true that the test suite already catches rounding errors, but I think it would be nicer if they were caught in a test that belongs to the function that has the error, so I added this one test: https://github.com/exercism/elixir/pull/1100

@jnnks In general we do accept pull requests. We welcome pull requests for changes that were agreed on in GitHub issues first 🙂 but I had a lot of spare time today and I felt like adding the test myself 😇.
