### ISSUE TITLE
Missing .gitignore files

### ISSUE THREAD

**Issue by Tyyagoo** [exercism/elixir#1097]
### Problem

Some exercises doesn't have a .gitignore file, allowing inattentive students to end up committing unwanted files.
_e.g. _build folder_

### Examples

- affine-cipher
- circular-buffer
- complex-numbers
- darts
- house
- rational-numbers
- react
- resistor-color-duo
- resistor-color-trio
- square-root
- variable-length-quantity
- zebra-puzzle

_If this is really a unexpected behavior, I can submit a pull request to fix it._

**Comment by glennj** [comment]
I think they might be referring to students commit exercise to a personal git repo. I do this

**Comment by Tyyagoo** [comment]
I double-checked all the exercises and found only those others that were missing .gitignore

- book-store
- food-chain
- go-counting
- knapsack
- pov
- proverb
- rectangles
- satellite
- sgf-parsing
- two-bucket
- word-search
