### ISSUE TITLE
city-office address_map documentation test should be insensitive to key order

### ISSUE THREAD

**Issue by adamwight** [exercism/elixir#1124]
In the type documentation test [here](https://github.com/exercism/elixir/blob/1b21ae1ca610de97db79e76db890503ba75ce466/exercises/concept/city-office/test/form_test.exs#L211), we assert that the `address_map` keys are listed in a specific order, matching the order of keys in the `address_tuple`.  This should be relaxed to allow the keys in any order, by normalizing the docstring or making the test dynamic.  A standard practice is to alphabetize map keys, this should be considered correct as well.

**Comment by angelikatyborska** [comment]
Sorry for the late response 🙏. I opened a PR that will fix this.
