### ISSUE TITLE
lasagna exercise could integrate `alarm` into the rest of the module

### ISSUE THREAD

**Issue by adamwight** [exercism/elixir#1125]
Don't burn dinner!  If a lasagna has been in the oven too long and remaining_minutes_in_oven is called, by all means sound the alarm.

The drawback of my suggestion is that it encourages a mixed return type which can be annoying to work with.  Maybe this exercise would be a good place to also introduce the `{:ok, minutes :: integer} | {:error, "alarm"}` paradigm as well?

**Comment by angelikatyborska** [comment]
@adamwight That you for the ideas, but they don't fit the scope of this exercise. This exercise teaches the very basics, which are defined as:
- Know what a variable is.
- Know how to define a variable.
- Know how to define a function.
- Know how to return a value from a function (implicit return).
- Know how to call a function.
- Know that functions must be defined in modules.
- Know how to define an integer literal.
- Know how to define a string literal.
- Know how to use mathematical operators on integers.

Your first suggestions includes using one of: `if`, `case`, or `cond`, and your second suggestion includes using both atoms and tuples. All of those are existing concepts taught by other exercises that come after `lasagna`. Incorporating them into `lasagna` would make `lasagna` too big.
