### ISSUE TITLE
Specify behavior for `HighScore.reset_score` when player doesn't exist

### ISSUE THREAD

**Issue by adamwight** [exercism/elixir#1126]
The function should probably add the new player and reset their score.  Alternatively, it could throw an error.

**Comment by adamwight** [comment]
I like the direction you're going in—I was thinking in terms of a real-world program which needs to be robust to every edge case, but in this context the requirements only have to be specific enough to satisfy the tests, and the tests can be as thorough or as scant as we wish.

However, there's already a test written for "resetting score for non-existent player sets player score to 0", so either the instructions should include that detail, or the test case should be removed.  Either fix is perfectly valid!

**Comment by angelikatyborska** [comment]
@adamwight A test for this case already exist:
https://github.com/exercism/elixir/blob/8aa3bb8ec60206c923c31fb89f5d959f95c39a88/exercises/concept/high-score/test/high_score_test.exs#L95-L101

Is this enough and can we close the issue, or is the issue about more than just the test?

**Comment by angelikatyborska** [comment]
Thanks! Here's a fix:
