### ISSUE TITLE
 State of Tic Tac Toe: test 8 is an invalid game

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/elixir#1127]
Test 8 has the following test data

"O.O\nXXX\n.O.\n" which is an invalid game as X won before O's last turn

**Comment by jiegillet** [comment]
You're right, and we can fix it by removing (let's say) the very first O.
Could you open an issue/PR on problem-specifications as well? I will approve it.

**Comment by chriseyre2000** [comment]
I was going to do that and add one more test with a continue past without a second win.

**Comment by jiegillet** [comment]
Great! To be as consistent as possible, let's wait for the specs to change before updating the tests here.

**Comment by chriseyre2000** [comment]
Raised the problem specification as an issue:

https://github.com/exercism/problem-specifications/issues/2030

Only fixing the direct problem. I am now going to raise a PR to fix it.

**Comment by angelikatyborska** [comment]
Fixed in https://github.com/exercism/elixir/pull/1129
