### ISSUE TITLE
Analysis of "File Sniffer"

### ISSUE THREAD

**Issue by TBK145** [exercism/elixir#1152]
Hi, I was doing the "File Sniffer" exercise, and this was my solution:
```
defmodule FileSniffer do
  def type_from_extension("exe"), do: "application/octet-stream"
  def type_from_extension("bmp"), do: "image/bmp"
  def type_from_extension("png"), do: "image/png"
  def type_from_extension("jpg"), do: "image/jpg"
  def type_from_extension("gif"), do: "image/gif"

  def type_from_binary(<<0x7F, 0x45, 0x4C, 0x46, _rest::binary>>), do: "application/octet-stream"
  def type_from_binary(<<0x42, 0x4D, _rest::binary>>), do: "image/bmp"
  def type_from_binary(<<0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, _rest::binary>>), do: "image/png"
  def type_from_binary(<<0xFF, 0xD8, 0xFF, _rest::binary>>), do: "image/jpg"
  def type_from_binary(<<0x47, 0x49, 0x46, _rest::binary>>), do: "image/gif"

  def verify(file_binary, extension) do
    case {type_from_binary(file_binary), type_from_extension(extension)} do
      {type, type} -> {:ok, type}
      _ -> {:error, "Warning, file format and file extension do not match."}
    end
  end
end
```
But for some reason it still gave me this feedback:
> Essential
Even though there could be other valid ways to solve this exercise, for the sake of mastering bitstrings please match the first few bytes of the argument of type_from_binary/1 with the special form <<>>.

I tried solving for the problem myself, but couldn't find what was actually causing it.

**Comment by TBK145** [comment]
I think it can be solved by creating a test that inputs a binary with only the last byte missing. However, some people will have made a fallback function, and some people won't, so it will either be some random output, or it will be a FunctionClause error. So I think before we add that test we should add something in task 2 like "Return "not recognized" if it doesn't match any of the above".

**Comment by Lgdev07** [comment]
In this scenario, I believe we could expect the error because the scope of the files is already defined in the instructions, so it is clear to the student that we won't have another file type.

Please see in the PR if this makes sense.
