### ISSUE TITLE
Wrong assertion for update_score

### ISSUE THREAD

**Issue by sreejithec** [exercism/elixir#1154]
https://github.com/exercism/elixir/blob/main/exercises/concept/high-score/test/high_score_test.exs

Line 142

@tag task_id: 5
    test "update score for existing player with non-zero score adds score to previous" do
      scores =
        HighScore.new()
        |> HighScore.add_player("José Valim")
        |> HighScore.update_score("José Valim", 1)
        |> HighScore.update_score("José Valim", **486_373**)

      assert scores == %{"José Valim" => 486_374}     <---------------------------- Wrong value
    end

The assertion given here is wrong. I am not able to pass the tests because of that.

**Comment by angelikatyborska** [comment]
Hi! Which value would you expect instead and why?

**Comment by jiegillet** [comment]
@sreejithec the scores should add up, so the value `1 + 486_373 = 486_374` is correct.
I'm going to close the issue, feel free to comment again if you have further questions.
