### ISSUE TITLE
Implement new concept exercise: `records`

### ISSUE THREAD

**Issue by maco** [exercism/elixir#1161]
I only just found out records exist, and apparently I now check the Exercism concept explanations before the official docs when it comes to getting a big-picture view of a thing (versus for seeing the API), and I noticed it's not here.

# Learning objectives
* defrecord
* is_record

# Out of scope
I am not sure if explaining require/use in the same exercise would be a good idea. It's a lot of difficult concepts at once. But maybe it makes sense?

# Concepts
records

# Prerequisites
tuples

Possibly this also points to a "using Erlang libraries in Elixir" concept as well, since `extract` is for pulling Erlang records into an Elixir program. 

# Practice exercises
perhaps one of the tuple exercises could be converted to a records exercise?

**Comment by angelikatyborska** [comment]
Do you think it makes sense to teach people about a concept that you yourself never had to know until now even though you work with Elixir professionally (I assume)? I never had to work with them either and it has been 5 years of using Elixir for me 🤔

**Comment by maco** [comment]
🤷🏼‍♀️ I haven't had a reason to touch ASTs until now, and I've never had to include Erlang libraries outside a tutorial, but those are in the track. (Clearly I haven't gotten that far down the track since I didn't realize the latter was in there already.)

(And I'm not doing Elixir professionally anymore. I did for about a year and a half, on a Phoenix app, which required more understanding libraries than understanding advanced language stuff.)

Just figured I'd suggest it. Up to you.

**Comment by angelikatyborska** [comment]
@jiegillet @neenjaw @chriseyre2000 @Cohen-Carlisle what's your opinion? Are records used in Elixir enough to justify adding them to the concept tree?

**Comment by neenjaw** [comment]
As I understand it, they exist as they are an Erlang primitive, but they are generally irrelevant in the Elixir context. @NobbZ can probably provide insight if they are still relevant from an Erlang perspective.

**Comment by NobbZ** [comment]
I have never used them except to interop with Erlang code.

I don't consider them important on the higher level, and as far as I can tell, even in Erlang they seem to become less important since maps are used more frequently.

At least in the public interfaces.

I still see them used often in a gen servers state, which in turn you rarely have direct access to.

So I don't think they deserve much of attention, and if at all they should be part of, or extend, the Erlang interfacing concepts.

**Comment by chriseyre2000** [comment]
They are less easy to use than structs although they can theoretically be
faster. Not used in anger beyond the introduction to Erlang book.

**Comment by angelikatyborska** [comment]
I'm going to draw a conclusion from all those comments that putting our efforts into teaching this concept in Elixir wouldn't be worth it and close this issue.
