### ISSUE TITLE
Resistor Color Trio - wrong assertions in README compared to the exepcted result in tests

### ISSUE THREAD

**Issue by belgoros** [exercism/elixir#1167]
As for the README content, the method should return String:

> So an input of `"orange", "orange", "orange"` should return:
> 
> "33 kiloohms"

But the tests assert it differently by expecting it to be a tuple:
```elixir
colors = [:orange, :orange, :black]
output = ResistorColorTrio.label(colors)
expected = {33, :ohms}
```

**Comment by angelikatyborska** [comment]
Hi, the READMEs (problem description) are global for the whole platform. They come from this repository: https://github.com/exercism/problem-specifications

We can't edit them for Elixir specifically. We generally expect students to pay attention to the tests more than the README.

**Comment by belgoros** [comment]
OK, got it, thank you.
