### ISSUE TITLE
Binary-search elixir, first test taged as pending

### ISSUE THREAD

**Issue by meatball133** [exercism/elixir#1175]
The first test is taged as pending

**Comment by meatball133** [comment]
Made a pull request with fix

**Comment by angelikatyborska** [comment]
@meatball133 A GitHub tip: when opening a pull request, you can include in that pull request comment the word "resolves" or "fixes" followed by the URL of a GitHub issue. GitHub will then automatically close the issue when the PR gets merged.

**Comment by meatball133** [comment]
Thanks, will do that next time :)
