### ISSUE TITLE
Should we tweak the bitwise example in Secrets introduction?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/elixir#1189]
The introduction says:

> Here is an example how to use a bitwise function:

The example it gives is:

```
Bitwise.bsl(1, 2)
# => 4
```

However, it's not immediately clear which number is being shifted and which number represents how many places it is shifted, because `Bitwise.bsl(1, 2)` and `Bitwise.bsl(2, 1)` both result in 4.

Would it make sense to use a different value in the example to help clarify? E.g.

```
Bitwise.bsl(1, 3)
# => 8
```

If this seems like a good change, I'd be happy to put in a PR.

**Comment by angelikatyborska** [comment]
That indeed sounds like a better example. A PR would be great 💜
