### ISSUE TITLE
Add reminder for elem/2 to Binary Search exercise.

### ISSUE THREAD

**Issue by danielniccoli** [exercism/elixir#1202]
I just completed the first Tuples and Recursion exercise, and returned to Tuples for the second exercise: Binary Search. In this exercise, you need to access values by their key.

The first Tuple exercise briefly mentions `elem/2`.

> In practice, tuples are created in Elixir using curly braces. Elements in a tuple can be individually accessed using the elem/2 function using 0-based indexing

However, `elem/2` is not needed to complete this exercise. By the time one returns to the second Tuple exercise, this information may already be forgotten. It would be good, if the Binary Search exercise would offer some hints to how it can be completed, namely the `elem/2` function.

**Comment by angelikatyborska** [comment]
Hi! Thank you for reporting, but we as a rule do not provide hints for practice exercises (there are a few exceptions, but those are very old and generally not maintained).

Students are expected to go back to the concept page or Elixir's documentation to review the concept if they are struggling with it in a practice exercise.
