### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by vcborsolan** [exercism/elixir#1205]
Hello folks, I'm opening this issue to discuss if this repository will participate in the 202 digital ocean [hacktoberfest](https://hacktoberfest.com/participation/#maintainers).

If so, let's review the issues and add the labels/tags for valid contributions.

**Comment by iHiD** [comment]
No, Exercism doesn't generally participate in Hacktober fest as it creates more work for maintainers than it creates value for Exercism. If you create PRs that are in line with the repo (ie work on existing issues etc) then we maybe tag them as hacktoberfest-accepted (or whatever the label is nowadays) but unsolicited minor PRs will normally be tagged as `invalid`. 

Thanks for checking.
