### ISSUE TITLE
Wrong output in german-sysadmin introductions example?

### ISSUE THREAD

**Issue by dmarcoux** [exercism/elixir#1240]
I would expect the line 25 below to be `# => [58, 41]`, since this is the output from `[?:, ?)]`.

https://github.com/exercism/elixir/blob/b578cf12ce71f894b0c590a982857318369138cb/exercises/concept/german-sysadmin/.docs/introduction.md?plain=1#L24-L25

If this is truly a mistake, I would send a PR to address this.

**Comment by angelikatyborska** [comment]
Your expected output and the output currently in the doc is actually the same value:
```elixir
iex()> [58, 41] == ':)'
true
```

Is is possible that you have configured your own iex to always print charlists as lists of integers (`[58, 41]`)? As far as I know, it is still the default behavior in Elixir 1.14.2 to print charlists as charlists (`':)'`)

**Comment by dmarcoux** [comment]
> Is is possible that you have configured your own iex to always print charlists as lists of integers (`[58, 41]`)?

Oh right, I did configure IEx to always print charlists as lists of integers. Sorry for the noise!

This is what I have in my global IEx configuration file (`~/.iex.exs`):

```elixir
IEx.configure(inspect: [ charlists: :as_lists ])
```

Thank you @angelikatyborska for the quick reply. I wish you a great day!
