### ISSUE TITLE
Directory names of exercises don't match application names 

### ISSUE THREAD

**Issue by dmarcoux** [exercism/elixir#1259]
Hi,

I'm going through the exercises of the Elixir track and as an excuse to learn how to setup continuous integration for Elixir projects, I decided to create an [umbrella project](https://github.com/dmarcoux/exercism-elixir) to contain all the exercise projects I've completed so far. I then have GitHub actions checking for a few things like formatting, compilation errors and tests. I'm getting errors in my continuous integration like:

```
** (Mix) Umbrella app :boutique_suggestions is located at directory boutique-suggestions. Mix requires the directory to match the application name for umbrella apps. Please rename the directory or change the application name in the mix.exs file.
```

or 

```
** (Mix) Umbrella app :remote_control_car is located at directory remote-control-car. Mix requires the directory to match the application name for umbrella apps. Please rename the directory or change the application name in the mix.exs file.
```

I know this isn't how this Exercism track is intended to be used... but I don't see why matching directory names and application names would be bad. Would you be against a PR which renames the exercise directories to have them match their application names? I'm happy to send one :slightly_smiling_face:

**Comment by dmarcoux** [comment]
I looked at other Exercism tracks and the `problem-specifications` repository, they are all using dashes in the directory names of exercises, so I don't see how this issue could be resolved by renaming the exercise directories. As for the Elixir application names, they could be changed, as an example, from `:remote_control_car` to `:"remote-control-car"`.

**Comment by jiegillet** [comment]
Hi @dmarcoux.
I appreciate the thought, in fact I myself opened a very similar PR before (it got closed), but we are not looking for a change like this. 
Like you discovered, the directory names are standardized over Exercism tracks to match the exercise slugs, so they should not be touched. 
But at the end of the day, such a big change has the potential of breaking many non-obvious things and wouldn't bring much benefit to the students, so all in all it's not worth doing for us. It seems like a good learning exercise on your side though, feel free to fork the repo and try it out :)

**Comment by dmarcoux** [comment]
No worries, this is exactly the answer I expected. I still asked just in case, but it's all good.

Thank you for your reply.
