### ISSUE TITLE
Inappropriate and irrelevant comments in "Simple Cipher" exercise description

### ISSUE THREAD

**Issue by lauramcastro** [exercism/elixir#1262]
The exercise description contains a couple of references to "_our little sister_" [1] and "_your kid sister_" [2] that are both inappropriate (reinforcing ill stereotypes about girls and sibblings' relationships) and irrelevant for the understanding of the exercise.

I'd suggest the quoted text simply be removed.

[1] _"(...), but we are lucky that generally our little sisters are not cryptanalysts."_
[2] _"Shift ciphers are no fun though when your kid sister figures it out."_

**Comment by angelikatyborska** [comment]
Hi! Thank you for the issue report, but the maintainers of the Elixir track have no decision power over this text - all exercise descriptions come from a central repository and must be the same in all programming languages on Exercism. The repository is https://github.com/exercism/problem-specifications, but at the moment it has paused accepting community contributions. As long as the pause is in place, the right place to report those kinds of problems is the forum: https://forum.exercism.org/

**Comment by lauramcastro** [comment]
Thanks for the info, and sorry for the misplacement!

I'll report this on the forum, then.
