### ISSUE TITLE
[log-level] Misused trailing question marks

### ISSUE THREAD

**Issue by saantonandre** [exercism/elixir#1323]
The "Log Level" functions have a parameter called `legacy?` used to indicate a boolean value, this may be incorrect because the convention applies to [**functions**](https://hexdocs.pm/elixir/main/naming-conventions.html#trailing-question-mark-foo) that return a boolean, other than that it just creates more confusion since naming convention haven't yet been covered (related issue https://github.com/exercism/elixir/issues/1283)

**Comment by angelikatyborska** [comment]
Hi! Using the same convention (trailing question mark) for variables as for function names is perfectly ordinary in Elixir. Here's a few examples from the Elixir language repository:
- https://github.com/elixir-lang/elixir/blob/main/lib/elixir/pages/patterns-and-guards.md?plain=1#L449 
- https://github.com/elixir-lang/elixir/blob/main/lib/logger/lib/logger/app.ex#L9-L10
- https://github.com/elixir-lang/elixir/blob/main/lib/mix/lib/mix/tasks/local.hex.ex#L46

I'd rather add a mention about this in the introductions than rename the variables - people need to be ready for this pattern 🙂 I should have time to work on https://github.com/exercism/elixir/issues/1283 soon
