### ISSUE TITLE
Update all Elixir Exercism repos to use Elixir 1.15 and OTP 26

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir#1331]
An example of how to do it can be seen in previous PRs for Elixir 1.14:
- https://github.com/exercism/elixir/pull/1191 (note that the oldest Elixir version gets dropped)
- https://github.com/exercism/elixir-test-runner/pull/92
- https://github.com/exercism/elixir-analyzer/pull/325
- https://github.com/exercism/elixir-representer/pull/72

**Comment by dabaer** [comment]
@angelikatyborska I was just peeking into this when I noticed you assigned this ha!

At first glance some minor changes to mix.exs and an upgrade to dialyxer.

I'm running into an issue with the TakeANumberDeluxe test (🤔 didn't we just fix an issue on that one?) where the GenServer is exiting on invalid configuration. Just going over that at the moment

**Comment by angelikatyborska** [comment]
Ah, sorry 😅 I opened a draft PR https://github.com/exercism/elixir/pull/1332 - draft because I don't know yet how to handle that failing TakeANumberDeluxe test. Let me know if you figure it out!

**Comment by dabaer** [comment]
All good! I'll dig it out and then move over to your PR discussion

**Comment by angelikatyborska** [comment]
@dabaer If you're interested in helping out further, now that https://github.com/exercism/elixir/pull/1332 is merged, you could open PRs for the 3 other repositories

**Comment by dabaer** [comment]
Will do 🎉

**Comment by dabaer** [comment]
♥️💙💚💛💜

**Comment by angelikatyborska** [comment]
It's live and I wrote a little site update:
![Screenshot 2023-07-02 at 09 04 03](https://github.com/exercism/elixir/assets/7852553/9d22d39f-11e6-4ecc-9e09-76a820c1dbb9)

**Comment by dabaer** [comment]
It was a wild ride with breaking changes, and certainly one of the largest PR threads I've ever seen.

Thank you and @neenjaw for your guidance on these commits, it's really expanded my knowledge of Elixir!
