### ISSUE TITLE
Lasagna exercise 

### ISSUE THREAD

**Issue by basmoura** [exercism/elixir#1341]
since the function `expected_minutes_in_oven` returns `40` as a default value, the function `remaining_minutes_in_oven/1` subtract the parameter value from the default value returned by the function `expected_minutes_in_oven` and `preparation_time_in_minutes/1` logic is the number of layers * 2  the return expected for the `function total_time_in_minutes(1, 30)`  should be `12`, right? 

```elixir
### total_time_in_minutes/2 => preparation_time_in_minutes/1 + remaining_minutes_in_oven/1

total_time_in_minutes(1, 30)
preparation_time_in_minutes(1) => 1 * 2 = 2
remaining_minutes_in_oven(30) => 40 (default value of expected_minutes_in_oven) - 30 = 10

=> 10 + 2 = 12
---
total_time_in_minutes(4, 8)
preparation_time_in_minutes(4) => 4 * 2 = 8
remaining_minutes_in_oven(30) => 40 (default value of expected_minutes_in_oven) - 8 = 32

=> 8 + 32 = 40
```

Using the Task 4 instructions example:

![image](https://github.com/exercism/elixir/assets/3411986/fc56c72e-861c-4f3e-b0db-3fb8174a7a0e)

```elixir
total_time_in_minutes(3, 20)
preparation_time_in_minutes(3) => 3 * 2 = 6
remaining_minutes_in_oven(20) => 40 (default value of expected_minutes_in_oven) - 20 = 20
=> 6 + 20 = 26
```

Here is my solution:

```elixir
defmodule Lasagna do
  # Please define the 'expected_minutes_in_oven/0' function
  def expected_minutes_in_oven, do: 40
  
  # Please define the 'remaining_minutes_in_oven/1' function
  def remaining_minutes_in_oven(minutes) do
    expected_minutes_in_oven() - minutes
  end
  
  # Please define the 'preparation_time_in_minutes/1' function
  def preparation_time_in_minutes(layers), do: layers * 2 

  # Please define the 'total_time_in_minutes/2' function
  def total_time_in_minutes(layers, minutes) do
    preparation_time_in_minutes(layers) + remaining_minutes_in_oven(minutes)
  end

  # Please define the 'alarm/0' function
  def alarm!, do: "Ding!"
end
```

All my previous tests before Task 4 is working well
![image](https://github.com/exercism/elixir/assets/3411986/98b4a296-bea6-4aec-b4d1-bec479a9889b)

Here is the output of Task 4
![image](https://github.com/exercism/elixir/assets/3411986/776668b1-4ea0-4793-ba34-f99530a113cc)

**Comment by dabaer** [comment]
The `total_time_in_minutes` function should only calculate the amount of time that has been spent preparing and cooking your lasagna, but you are using `remaining_minutes_in_oven` which returns units of work that haven't been completed yet, which is causing those tests to fail.

**Comment by basmoura** [comment]
thank you
