### ISSUE TITLE
Phone Number exercise: difference between tests in exercise folder vs online Test runner

### ISSUE THREAD

**Issue by AliNisarAhmed** [exercism/elixir#1349]
When solving the exercise [Phone Number](https://exercism.org/tracks/elixir/exercises/phone-number) on my local environment, all my tests were passing and I submitted with the CLI, however, the online test runner reported 4 tests failing on my first iteration. The difference was in the following error strings 
- "area code cannot start with zero" vs "area code cannot start with 0"
- "area code cannot start with one" vs "area code cannot start with 1"
- "exchange code cannot start with zero" vs "exchange code cannot start with 0"
- "exchange code cannot start with one" vs "exchange code cannot start with 1"

Looking at other solutions, I think they are all supposed to be `zero` and `one`, but somehow got changed in the online test runner. 

[Link to test file](https://github.com/exercism/elixir/blob/main/exercises/practice/phone-number/test/phone_number_test.exs)

I can create a PR if I know where is the online test runner code

## Screenshots

![image](https://github.com/exercism/elixir/assets/35175560/10c41148-0d28-4d28-8995-d38c27d84e87)
![image](https://github.com/exercism/elixir/assets/35175560/8a63e47a-492a-4b7f-85b7-30f137899738)
![image](https://github.com/exercism/elixir/assets/35175560/5a6890ca-730e-4c98-8fe8-63f30ae632a7)
![image](https://github.com/exercism/elixir/assets/35175560/70751bec-159d-48c3-a31e-13d398238247)
![image](https://github.com/exercism/elixir/assets/35175560/e3270481-245a-4c25-a85a-036f01d99e5c)
![image](https://github.com/exercism/elixir/assets/35175560/b77e2023-cd55-4e66-acee-0cf83b375039)

**Comment by angelikatyborska** [comment]
Hi! Did you by any chance edit the test file when you were solving the exercise locally? That is the only explanation that I can think of.

The test file have been using the error message ` "area code cannot start with zero"` and that's the expected version. I don't think we ever had a version of the test that expected the error message ` "area code cannot start with 0"`.

**Comment by AliNisarAhmed** [comment]
If you have checked and the two test files match, then yes it's most likely that I may have messed up my local test file (although I do not recall ever changing them). 

Anyways, I'll close the issue. Thanks
