### ISSUE TITLE
[RPG Character Sheet] Misleading the 5th question

### ISSUE THREAD

**Issue by konradrr** [exercism/elixir#1382]
Hey! I believe that for the 5th question, the intention was to display `player` map using `IO.inspect/2` and then **return the map** ([see the expected code example](https://github.com/exercism/elixir/blob/main/exercises/concept/rpg-character-sheet/.docs/instructions.md?plain=1#L62)).

There's no test checking it and what's more misleading, the analyzer suggests that the last call in the function should be `IO.inspect` ([see here](https://github.com/exercism/elixir-analyzer/blob/main/lib/elixir_analyzer/test_suite/rpg_character_sheet.ex#L54)).

IMO adding the missing test and removing/changing the analyzer to check if the map was returned should do the work 🙂

**Comment by jiegillet** [comment]
Hi! 

I don't think there is anything misleading here.
`IO.inspect(x)` will print the content of `x` in the console, but also return `x` unchanged, so there is no need to return `x` after that. I believe this task is meant to teach that aspect of `IO.inspect`.

This is addressed in the hints, but I see that it is not explained in the `introduction.md`, it's only explained in the `about.md` which is visible after the exercise has been solved. Maybe we should move it to the introduction since it's directly used in the exercise.

**Comment by angelikatyborska** [comment]
Hi! Just like @jiegillet said, the point of this task in this exercise is teaching that `IO.inspect` returns the value unchanged, so there is no need to add any explicit returns at the end of the `run` function - the call to `IO.inspect` should be the last expression in that function.

> There's no test checking it

@konradrr I'm not sure what you mean. There is a test that checks that a map is returned https://github.com/exercism/elixir/blob/ea407685c41c660e2642a6a9ba69f34ef852365d/exercises/concept/rpg-character-sheet/test/rpg/character_sheet_test.exs#L91-L99 and there is a test that checks that the map was printed to IO https://github.com/exercism/elixir/blob/ea407685c41c660e2642a6a9ba69f34ef852365d/exercises/concept/rpg-character-sheet/test/rpg/character_sheet_test.exs#L118-L131 . What else is missing?

> This is addressed in the hints, but I see that it is not explained in the introduction.md

@jiegillet I am seeing this text in the introduction:

> If you need a tool for debugging that will allow you to write any value to standard output, use `IO.inspect` instead. `IO.inspect` returns the value it was passed unchanged, so it can be inserted in any point in your code. It also accepts many options, for example `:label`, that will allow you to distinguish it from other `IO.inspect` calls.

Is this not enough information about `IO.inspect`? What else is missing?

**Comment by konradrr** [comment]
@jiegillet @angelikatyborska You're completely right! I created the issue late at night without double-checking, and I guess that I assumed at the moment that `IO.inspect` returns `:ok` like `IO.puts` does. My bad!

That's a lesson for me to not create issues at the night! 🙈 Anyway, thanks for the very quick response, and sorry for the confusion.

**Comment by jiegillet** [comment]
@angelikatyborska yup, you're right. I was comparing the about and the intro, I saw the about had a whole section with `IO.inspect` and the intro didn't, so I missed the part about `IO.inspect` in the intro.
