### ISSUE TITLE
Lucas Numbers

### ISSUE THREAD

**Issue by everaldo** [exercism/elixir#1497]
Hi! This is my first issue, so I'm sorry if I'm not following some guidelines.

Regarding the Elixir Exercise "Lucas Numbers" 

https://github.com/exercism/elixir/tree/main/exercises/concept/lucas-numbers

I have a complaint/suggestion.

The task "catch bad arguments" should come first

![Screenshot_20240620_211132](https://github.com/exercism/elixir/assets/892012/83b25e40-b907-4e59-9f3b-dd64eb3bc044)

Because I've spent one hour trying to debug my solution and I was always getting a timeout. So I realized the following.

If I've made by brute force `Enum.take(25)` it worked without timeout, for all test examples.

But when I was typing `Enum.take(count)` I was getting a timeout/error. After one hour, I've realized that I was getting this error because count was not an integer number, or it was a negative number.

So my suggestion is to make the task "catch bad arguments" as the first or the second. So when the developers want to resolve the stream to a list, they won't get those strange time out errors.

Thanks a lot!

**Comment by angelikatyborska** [comment]
Thank you for the suggestion! That's a very good idea.
