### ISSUE TITLE
Newsletter task instruction confusing 

### ISSUE THREAD

**Issue by Nanonej** [exercism/elixir#1499]
https://github.com/exercism/elixir/blob/587f44e54cb2dd08aa6209ca19a79c902f9ba6fa/exercises/concept/newsletter/.docs/instructions.md?plain=1#L47

Hey! I just did this exercise with a friend and we got stuck as we were confused by the task instruction and what the tests were checking.

The task ask us to log the email address when the passed function return `:ok`.
To do it we're instructed to open and close the logfile and to `Make sure to do it as soon as the email is sent.`
So we both understood by that, that we should enumerate the email list and try to send the email and thus logging it on success by opening and closing the logfile on **each** one of them.

But to do that we used the mode `:append` on the File.open to prevent the overwrite, which was highlighted as an essential issue when submitting the exercise.  Also we had to manually reset the logfile on the first operation of this function task as the test 14 was checking that.

So I think either some information are missing in the instruction of this task or the part `Make sure to do it as soon as the email is sent` is a bad formulation of what it's expected.

**Comment by angelikatyborska** [comment]
The sentence "make sure to do it as soon as the email is sent." refers to the closest preceding instruction which is "write the email address to the log file, followed by a new line".

To make this clearer, we could replace "to **do it**" with a repetition of the previous instruction, for example:

> Implement the `Newsletter.send_newsletter/3` function. It should take a path of the file with email addresses, a path of a log file, and an anonymous function that sends an email to a given email address. It should read all the email addresses from the given file and attempt to send an email to every one of them. If the anonymous function that sends the email returns `:ok`, write the email address to the log file, followed by a new line. Make sure **to write the email address to the log file** as soon as the email is sent to that one email address. **After all sending is done**, close the log file.

**Comment by Nanonej** [comment]
> The sentence "make sure to do it as soon as the email is sent." refers to the closest preceding instruction which is "write the email address to the log file, followed by a new line".

Yes, that's exactly why we got confused!

Maybe only the last modification is necessary as it's what we could have needed to understand at which step we were expected to open/close the logfile.
"**After all sending is done**" make it clear for the close and so the open before.
`Make sure to do it as soon as the email is sent` for the write seemed clear enough :slightly_smiling_face:.
