### ISSUE TITLE
'Series' problem template inconsistencies to other problems.

### ISSUE THREAD

**Issue by Lasamat** [exercism/elixir#1517]
In the starter template the parameters 's' and 'size' have underlines before them. This looks like an error.

```elixir
defmodule StringSeries do
  @doc """
  Given a string `s` and a positive integer `size`, return all substrings
  of that size. If `size` is greater than the length of `s`, or less than 1,
  return an empty list.
  """
  @spec slices(s :: String.t(), size :: integer) :: list(String.t())
  def slices(_s, _size) do
  end
end
```

**Comment by angelikatyborska** [comment]
Thank you for the bug report!

This is not an error. Argument names can start with an underscore to mark that they are supposed to be unused arguments. But most of the exercises don't use that feature in the solution stub file, so we can remove it from `series` as well.
