### ISSUE TITLE
'Bottle Song' Stub file inconsistent

### ISSUE THREAD

**Issue by Lasamat** [exercism/elixir#1519]
Hey,

so I found another stub file that has '_' for the method parameter names. Last time I wasn't as expressive but I know its not an error in Elixir but it makes no sense to have a stub that uses discard naming for the method parameter names that are supposed to be used.

[Link to file](https://github.com/exercism/elixir/blob/main/exercises/practice/bottle-song/lib/bottle_song.ex)

```elixir
defmodule BottleSong do
  @moduledoc """
  Handles lyrics of the popular children song: Ten Green Bottles
  """

  @spec recite(pos_integer, pos_integer) :: String.t()
  def recite(_start_bottle, _take_down) do
  end
end
```

**Comment by angelikatyborska** [comment]
The PR I opened because of your previous issue already fixes that: https://github.com/exercism/elixir/pull/1518/files

We just need to wait for @jiegillet to have some time take a look and approve the PR.
