### ISSUE TITLE
[Complex Numbers] inconsistencies between start template and tests.

### ISSUE THREAD

**Issue by Lasamat** [exercism/elixir#1525]
The specs say exp takes a complex number and returns a complex number but the tests contain a test case with a real number.

Snippet from the template.
```elixir
  @doc """
  Exponential of a complex number
  """
  @spec exp(a :: complex) :: complex
```

**Comment by angelikatyborska** [comment]
Which test exactly?

I checked the test suite for the `exp` function and as far as I can see, all expected return values in those tests are of the `complex` type, which is a tuple of two numbers. So I'm not sure where the problem is 🤔
