### ISSUE TITLE
Add topics to config.json

### ISSUE THREAD

**Issue by parkerl** [exercism/elixir#301]
The following exercises need topics added to `config.json`.

 - [ ] acronym
 - [ ] allergies
 - [ ] anagram
 - [ ] atbash-cipher
 - [ ] bank-account
 - [ ] beer-song
 - [ ] binary
 - [ ] binary-search
 - [ ] bowling
 - [ ] bracket-push
 - [ ] change
 - [ ] connect
 - [ ] crypto-square
 - [ ] custom-set
 - [ ] diamond
 - [ ] difference-of-squares
 - [ ] dot-dsl
 - [ ] etl
 - [ ] flatten-array
 - [ ] forth
 - [ ] gigasecond
 - [ ] grade-school
 - [ ] grains
 - [ ] hamming
 - [ ] hexadecimal
 - [ ] isogram
 - [ ] kindergarten-garden
 - [ ] largest-series-product
 - [ ] leap
 - [ ] list-ops
 - [ ] luhn
 - [ ] markdown
 - [ ] meetup
 - [ ] minesweeper
 - [ ] nth-prime
 - [ ] palindrome-products
 - [ ] parallel-letter-frequency
 - [ ] pascals-triangle
 - [ ] phone-number
 - [ ] prime-factors
 - [ ] pythagorean-triplet
 - [ ] queen-attack
 - [ ] rail-fence-cipher
 - [ ] raindrops
 - [ ] rna-transcription
 - [ ] robot-simulator
 - [ ] roman-numerals
 - [ ] run-length-encoding
 - [ ] saddle-points
 - [ ] scrabble-score
 - [ ] sieve
 - [ ] sublist
 - [ ] sum-of-multiples
 - [ ] triangle
 - [ ] wordy
 - [ ] zipper

**Comment by martinsvalin** [comment]
Do we have guidelines on what topics to use? I would feel more comfortable working through the missing topics if I had that.

I assume there's some value in keeping the number of topics smallish, avoid variations (lists, collections, enumerables), and maybe at a similar level of specificity.

I grabbed all the unique topics in config.json right now. This is the list (it already needs some cleanup).

```
["Algorithms", "Enumerations", "Integers", "Logic", "Pattern Matching", "Protocols", "Recursion", "Sorting", "Strings", "Structs", "Transforming", "Trees", "binary representation", "collections", "control flow", "encryption", "enumerables", "enumerations", "formatting", "lists", "maps", "math", "pattern matching", "recursion", "reduce", "sorting", "string formatting", "string processing", "strings", "structs"]
```

We should be able to come up with a reusable set of topics, and then give license to add more for an exercise that brings something unique to the table. Or will that have folks try to apply a predetermined set of topics, and kill the creative thinking?

**Comment by devonestes** [comment]
This is a tricky one, and I think that trying to find a set of topics that can be covered is going to be a pretty big set. My guidance would be pretty simple - pick whichever 2-4 things you think are covered by a given exercise, and we'll use that. These can be language features (like "Pattern Matching", "Protocols", etc.), or they can be topics that the exercise itself covers (like "Sorting", "Trees", etc.).

Once we have topics for all the exercises, then we can maybe stick to the limit of 4 per exercise, and if folks want to add one, then that can be handled on a case by case basis.

So, yeah, use your best judgement and I'm sure we'll be just fine. I think once all of them are done, then we can tackle individual issues like variations as they arise or at least once they're complete.

I could of course be wrong, but in general I trust the folks on here to do a really good job, and I haven't been let down yet! 🎉

**Comment by tleen** [comment]
There is a [list of example topics in problem-specifications](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt).
