### ISSUE TITLE
Update config.json for nextercism

### ISSUE THREAD

**Issue by devonestes** [exercism/elixir#353]
We have a new format for the `config.json` file, and we need to go though and do some selection of which exercises will be "core" exercises in the track, and which will be unlocked by those core exercises.

This might take a bit, and there will (hopefully) be a good amount of discussion around it, so I wanted to open an issue as a place for that discussion and a reminder to get it done!

**Comment by martinsvalin** [comment]
So what should we aim to cover in the "core"?

Solving familiar problems while trying out an unfamiliar language? Maybe `word-count` is a good base that many should find familiar? `bob` is obviously in all the tracks, it's almost synonymous with Exercism to me…

Problems that are well suited to learn more about FP. Recursion, higher order functions. I have a fondness for the `list-ops` exercise.

Problems that'll let you explore features specific to BEAM or to Elixir. Things like pattern matching, processes and message passing, perhaps macros. I don't think we need to worry about teaching the pipe operator, newcomers love it. Maybe structs are important to cover, in the Elixir-specific category.

I had fun with both macros and pattern matching when I did `roman numerals`, but maybe that exercise doesn't really push you towards it, it was more coming from me… but `rna transcription` almost begs for a pattern matching solution.

There's some OTP in `bank account`, and I wish we had more of it. I think there's an opportunity for exercises that guide you towards using `Flow`, for example. It's a little hard to imagine an exercism-scope exercise that has you set up distributed nodes…

I had fun implementing `zipper`, and it calls for structs.

Do we have any exercises that teach protocols? Well, `clock` wants an implementation of String.Chars. It wouldn't be hard to add or modify an exercise to implement Enumerable. I already mentioned zipper, where a bintree is needed, but I think there are several exercises that ask you to implement a data structure that is enumerable, they just don't require the protocol implementation. `custom-set` comes to mind.

Anyway… those are just some thoughts on the subject of what we should look for in a core set of exercises.

I have a question, though: should we aim to keep the core on the easy side, and keep the harder challenges in the side-quests?

**Comment by devonestes** [comment]
So, about the core exercises.

I think these should be of an increasing level of difficulty, starting with 2-3 of the "classic" ones (like `bob` and something like `word-count` or `rna-transcription`). At the very end I think we can have some more difficult problems, which can "unlock" the whole host of difficult problems we have. I also definitely think we should have `markdown` in the core exercises, since that would "unlock" any future other refactoring exercises we might add (and I like refactoring!).

So, I guess I'd say 10-15 of the easier exercises, and then maybe 4-5 of the harder ones at the end. Most of the exercises are on the easier side anyway, so I think this distribution would end up being like this anyway.

I like trying to cover as many of the key features of Elixir as possible in the core exercises!

I also think it would make sense to group types of exercises, like all the encryption ones, into a single "core" exercise and then a path that has all of those if folks want to explore those more.

So, here's my first take at some that I think would be good (not necessarily in this order):

`hello-world` (This just makes so much sense to start with, right?)
`bob`
`word-count` (and/or `raindrops`?)
`roman-numerals` (super familiar domain for folks, so it's nice to have)
`rna-transcription` (and this can unlock all the other DNA/RNA themed exercises)
`list-ops` (and/or `custom-set`?)
`beer-song` (and this can unlock some of the other text based exercises)
`binary-search` (classic recursive algorithm)
`clock`
`robot-simulator` (can be done with a struct or OTP)
`bank-account` (must be done with OTP)
`markdown`
`zipper`
`bowling` (or `minesweeper`, or `poker`?)
`forth` (or `dot-dsl`?)

We have room for a few more, too, but this seems like a pretty decent starting point for a set of 15-17!

I'd love to hear what some others think as well!

**Comment by tleen** [comment]
This is related to the now closed #301. I don't know Elixir at all, but `nextercism` is coming and it is worth taking a cursory look at the new structuring of config. I can suggest a few approaches that may help:

-  [configlet](https://github.com/exercism/configlet) can visualize your configuration in tree format now as you piece together the new structure &
- @jonmcalder came up with a nifty [visualizer](https://jonmcalder.shinyapps.io/exercism-config-viz/) &
- The Go track maintainers spent a lot of time looking at [core concepts for exercises](https://github.com/exercism/go/issues/830) to try and organize them, not sure how well it translates, but if it helps.
