### ISSUE TITLE
pig_latin_test.exs could be added cases for words beginning with multiple consonant letters

### ISSUE THREAD

**Issue by alarregoity** [exercism/elixir#359]
The test suite gives two rules:
 -   describe "first letter and ay are moved to the end of words that start with consonants" do
 -   describe "some letter clusters are treated like a single consonant" do
These two rules make us think that we must follow the "consonant rule" only for the first letter, or for the special "consonant cluster" cases given.

In contrast, wikipedia says: "For words that begin with consonant sounds, all letters before the initial vowel are placed at the end of the word sequence. Then, "ay" (some people just add "a") is added,"
Following wikipedia, any combination of consonant letters at the beginning of the word (not only the first letter) should be moved to the end of the word.
For instance, "pleasure" shoud be translated into "easureplay", not into "leasurepay".

I think that adding some test cases for the rule "all letters before the initial vowel are placed at the end ", with words beginning with multiple consonant letters, would produce more generic solutions.

**Comment by devonestes** [comment]
Thanks for the recommendation! This seems reasonable to me for sure. Would you care to try out a PR?

**Comment by rawkode** [comment]
Looks like this was closed by #366

**Comment by devonestes** [comment]
Yep, thanks for the reminder!
