### ISSUE TITLE
Exercises: Protein Translation issue in README.md

### ISSUE THREAD

**Issue by RamanBut-Husaim** [exercism/elixir#368]
Hello, everyone,

There is an issue in README.md - https://github.com/exercism/elixir/blob/master/exercises/protein-translation/README.md.

When the `STOP` sequence is described the following example is used

RNA: `"AUGUUUUCUUAAAUG"` => Codons: `"AUG", "UUU", "UCU", "UAG", "AUG"`

However `UAG` codon should be replaced with another STOP sequence - `UAA` according to RNA structure.

I would like to create a PR to address this.

**Comment by RamanBut-Husaim** [comment]
Here is the PR - https://github.com/exercism/elixir/pull/369

**Comment by RamanBut-Husaim** [comment]
@kytrinyx @devonestes Are you ok with such changes?

**Comment by devonestes** [comment]
@RamanBut-Husaim Hmm, I'm not really a biologist, so I wouldn't know what the correct `STOP` sequence is supposed to be here. I always just trust the READMEs in these cases, but that doesn't always mean they're totally correct, so yes, I'm always open to making things better! Can you link to something that shows that `UAA` is the correct `STOP` sequence?

**Comment by RamanBut-Husaim** [comment]
@devonestes Hello. Sure. It is a part of the same README.md :) https://screencast.com/t/hiIaTHhRhi

**Comment by devonestes** [comment]
PR merged!

**Comment by RamanBut-Husaim** [comment]
@devonestes Thanks a lot!
