### ISSUE TITLE
[Matrix] Check input/output data spec

### ISSUE THREAD

**Issue by mstranger** [exercism/elixir#400]
Hi, the exercise [Matrix](http://exercism.io/exercises/elixir/matrix/readme) defines the `%Matrix{}` struct, and all functions' specs from Matrix module uses it.
But test cases do not cover this feature. We can pass tests without using `%Matrix{}`. Maybe delete `defstruct` in matrix.exs file and edit specs? Or add input/output data check if using this struct is implied?

**Comment by martinsvalin** [comment]
I believe the tests are written to be as implementation agnostic as they
can be. The Matrix struct is external in the sense that it’s returned by
`from_list`, but the tests only exercise that function implicitly when
testing the rest of Matrix.

This makes it easy to change the internal implementation to something other
than struct, but still provides some hints and nudges at this difficulty
level for people new to Elixir.
tis 22 maj 2018 kl. 14:47 skrev mstranger <notifications@github.com>:

**Comment by devonestes** [comment]
Martin's right - we're giving a helpful pointer in a possible direction by defining the struct, but I don't think we should require it to pass the tests. Thanks for the issue, though!
