### ISSUE TITLE
Add test case to Acronym

### ISSUE THREAD

**Issue by pdgonzalez872** [exercism/elixir#401]
The most interesting aspect of this challenge was to solve the `HyperText` case, where there were two uppercase letters in a word. I enjoyed the challenge a lot. Unfortunately, some could argue that `HyperText` is really `Hypertext` in English. We can agree that whoever argues this kind of misses the point of the exercise and a great way to potentially practice recursion.

With that in mind, I wanted to add one additional test case where there are multiple uppercase letters in only one word. This is not really practical, as I was not able to come up with an example where this was true other than what one would use as a programming syntax: [`GetTopSpeed()`](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/methods).

This would break solutions that solved `HyperText` but did not account for multiple uppercase letters.

Thoughts on this?

**Comment by devonestes** [comment]
I hate closing issues, but I think we're covered pretty well on this point right now.
