### ISSUE TITLE
Core exercises

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/elixir#419]
I'd like to begin a conversation on core exercises and their ordering. I'll number my points for easier consideration.

1. I don't think `List Ops` should be core. It is pretty difficult, especially for beginners.
2. I don't think `Markdown` should be core. It is pretty difficult, especially if you find all the bugs that the tests aren't testing for. It's also harder to mentor (IMO), being a refactoring exercise.
3. I don't think Beer Song should be core. This one is probably more based on my opinion, but I've never been a big fan of the code-a-repeating-song type exercises.
4. The ordering seems off. `RNA Transcription` is one the easiest exercises, but comes after `Bob` and `Word Count`, which both involve dealing with non-ascii characters.

I have only gotten to `Markdown`, so I might have more opinions I haven't discovered yet. 😅

**Comment by angelikatyborska** [comment]
I would hate to see ListOps be removed as core. However, we have concerns about Markdown as recently three Elixir mentors (myself and Cohen included) confessed to avoiding mentoring this exercise as we ourselves feel overwhelmed by it.

**Comment by angelikatyborska** [comment]
I just wanted to point out that there is a student that commented on his incomplete solution to Bob that they are confused why Bob comes directly after Hello World because it's way more complicated: https://exercism.io/mentor/solutions/29edfb1c86b148459bce150ce5b35bea

I would agree that Hello World -> Leap -> RNA Transcription -> Bob is a better order.

**Comment by chriseyre2000** [comment]
I like having List Ops in the queue but it could be moved later.
Clock is really late in the list and I still have trouble with Zipper.

**Comment by angelikatyborska** [comment]
I guess this problem will be "resolved" by v3 not having "core" exercises anymore, but rather a tree of totally new "concept exercises".
