### ISSUE TITLE
Run tests with Elixir 1.7

### ISSUE THREAD

**Issue by amencarini** [exercism/elixir#423]
What's the best setup of the Travis matrix to include Elixir 1.7? Ideally that should run with OTP 21.

I've run [some trials](https://github.com/exercism/elixir/pull/422):
- Currently the tests fail with Elixir 1.7 because they use `Enum.chunk` instead of `Enum.chunk_every`. It's not a direct translation as a `:discard` option will have to be passed as a 4th parameter in some cases.
- Elixir 1.6.3 does not support OTP 21, but Elixir 1.6.6 does
- Elixir 1.5.3 does not support OTP 21

**Comment by devonestes** [comment]
I think we only need to support the most recent patch version of every minor version (so only 1.6.6, not 1.6.5), and we only need to support the last two minor verisons of Elixir (1.7 and 1.6), and last two major versions of Erlang (20 and 21).

If we need to update some deprecations as part of this, that happens occasionally. Y'all can go ahead and update those when you make the changes to the Travis config so CI continues. Usually those are just in the sample implementations, which isn't that big of a deal anyway.

**Comment by amencarini** [comment]
PR submitted 🙂
