### ISSUE TITLE
Markdown Exercise - File contains solution

### ISSUE THREAD

**Issue by pdgonzalez872** [exercism/elixir#428]
Hi!

Looks like the solution for Markdown gets pulled when you download the exercise. I'm sure that was not intended :)

To reproduce:
`exercism download --exercise=markdown --track=elixir`

Seems like (https://github.com/exercism/elixir/blob/master/exercises/markdown/markdown.exs) was not supposed to have the solution. I'll have a fix in a couple of minutes if you are interested.

Thanks!

**Comment by devonestes** [comment]
@pdgonzalez872 `Markdown` is actually the only refactoring exercise in exercism! I know, it's a little weird, but in that one you're not supposed to actually implement the markdown parser, but to refactor an existing (but very messy) solution.

**Comment by pdgonzalez872** [comment]
Haha! Sorry Devon! Thanks for clarifying!

Paulo
