### ISSUE TITLE
Proposed improvement to Binary Search

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/elixir#445]
I am proposing that we use this as the key "type" for the Binary Search:

defmodule BinaryTuple do

  @opaque t :: %BinaryTuple{tuple: Tuple}
  defstruct tuple: nil, 

  def new(tuple) when is_tuple(tuple) do
    %BinaryTuple{ tuple: tuple }
  end
  
  def at(%BinaryTuple = tuple, index) when is_integer(index) do
    Kernel.elem(tuple.tuple, index)
  end
  
  def size(%BinaryTuple = tuple) do
    tuple.tuple |> tuple_size()  
  end  
end  

It has all the properties that we need without having an obvious function to turn it into a list.

**Comment by devonestes** [comment]
@chriseyre2000 A struct that only has a single element has functionally no use other than an additional layer of indirection, which I think will confuse learners here. Structs are used to group related data, so if there's only one piece of data, then there's not much of a need for a struct.

Thanks for the recommendation, but if there's one thing that we've found is that making exercises more difficult to complete leads to fewer people progressing in the track, and that's not what we want, so this is going to stay as is for now.
