### ISSUE TITLE
Marking word-count

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir#463]
I think in >50% of the solutions I encounter, I have students that hard-code in the punctuation, and so, according to the mentoring notes, I suggest that they add the spanish case, and then have it pass the tests without hardcoding the punctuation in.

Might it be worth adding a small phrase in the problem description about punctuation and the goal to learn about using regular expression character classes?

Something along the lines of:

---

Given a phrase, count the occurrences of each word in that phrase.

For example for the input "olly olly in come free"

olly: 2
in: 1
come: 1
free: 1

Note: Your solution may encounter sentences with punctuation which should not be included in the count.  You solution will be expected to handle it without specific punctuation being hard-coded into your solution.

**Comment by devonestes** [comment]
Maybe we can include that as a sort of stretch goal or something?

**Comment by neenjaw** [comment]
Sure, I don't think it's a bad idea to make it a stretch goal as this is often a regex learning issue and not an elixir learning issue. 

But I think the mentoring notes imply that an acceptable solution should implement a regex which covers unexpected punctuation. 

From the [mentoring notes](https://github.com/exercism/website-copy/blob/master/tracks/elixir/exercises/word-count/mentoring.md):

> If a solution explicitly lists all punctuation characters necessary to make the tests pass, an alternative test case can be presented and the student asked to make this test pass too.

So maybe the wording in the mentoring notes should be the thing adjusted?

**Comment by devonestes** [comment]
This could be a disconnect between my thoughts and the thoughts on mentoring, but I usually think that if folks are “hacking” their exercises like that, it’s not such a problem. Coming up with a really good solution to these problems isn’t the point of doing the exercises - it’s learning and practicing the language. If they get the same language learning benefit from their hacks as they do from a “good” solution, I say let them have their shortcuts.

**Comment by neenjaw** [comment]
Ya, I can see your view. I guess I want to be consistent so that students get good consistent feedback.
