### ISSUE TITLE
Problem in Pangram tests

### ISSUE THREAD

**Issue by nathanchere** [exercism/elixir#466]
The instructions for Pangram clearly states:

"The alphabet used consists of ASCII letters `a` to `z`, inclusive, and is case
insensitive. Input will not contain non-ASCII symbols."

but then the final test is based entirely on handling non-ASCII characters.

I think this 'gotcha' test should be removed.

**Comment by neenjaw** [comment]
Or maybe the confusing about ASCII character should be eliminated. We work in an increasingly global world and we are lucky that elixir plays so nice with extended encodings like utf-8. 

What if the problem statement was modified to state "only be concerned with the English alphabet (a-z) for this problem, other characters should be disregarded but not cause the solution to crash."

**Comment by nathanchere** [comment]
The problem is ambiguity. "Other characters should be ignored" would still fail the test.

Whatever the requirements are should be stated clearly up front. Not require trying to work out what an outlier test is looking for.
