### ISSUE TITLE
Expand more exercises to start with an OTP umbrella app

### ISSUE THREAD

**Issue by trosel** [exercism/elixir#470]
The first five or so exercises can remain simple two-file solutions.

But is there any reason to avoid including a full OTP application download for later exercises? 

`exercism fetch` could just pull a full umbrella app. Then the README can explain the differences in structure

**Comment by NobbZ** [comment]
Umbrellas have nothing to do with OTP. "Umbrella projects" are just a nicer syntax for `path` dependencies in both, rebar and mix.

But I'm with you in the regard to use `mix` projects from the very beginning, as in real life you won't see anything else for elixir. There are already some issues around this, with the latest beeing #414.

**Comment by trosel** [comment]
Sorry for incorrect use of the word "umbrella". What I'm trying to get at is, learners should be encouraged to make use of OTP as early as possible. So they should get accustomed to how a supervisor connects with their exercise code as soon as possible. 

Perhaps Exercism is the wrong environment for this. But I think ideally, each solution would actually have the solution logic within one or two genservers that are managed by a supervisor.

**Comment by devonestes** [comment]
Exercism isn’t really the place for the kind of thing you‘re talking about. These problems are all _very_ simple. They‘re functions, mostly, and not applications that require supervision strategies.

We do have a couple that teach some OTP basics, and there‘s nothing actually stopping someone from going really wild and implementing solutions to these exercises in that fashion, but we are not going to „force“ folks to use those sorts of solutions for these problems.

First they need to learn the basic language constructs, and then they can learn the more advanced things like supervision.
