### ISSUE TITLE
bracket-push: renamed to matching-brackets

### ISSUE THREAD

**Issue by petertseng** [exercism/elixir#472]
In https://github.com/exercism/problem-specifications/pull/1501, bracket-push was renamed to matching-brackets in problem-specifications, therefore it is recommended that this track (which has the bracket-push exercise) also renames it.

The reasons for this recommendation:

* to name the exercise by its story, not by what it potentially teaches
* to avoid unnecessarily biasing the solution space

If this track decides to follow this recommendation, here are some things that may need a change:

* config.json (change the `slug` of the exercise; no need to change its `uuid`)
* name of the directory
* README (contains the name of the exercise)
* code

If you're not sure what needs to change, feel free to examine PRs to other tracks by looking at any PRs linked to https://github.com/exercism/problem-specifications/pull/1501.

When the rename is complete, the person who did the rename should close this issue; you don't need to ask for confirmation from the person who filed this issue (the person who filed this issue might not check back regularly).

If this track instead decides that accepting this recommendation is a bad idea for the track, then this issue should be closed upon making that decision, and none of the above steps should be taken.

**Comment by workingjubilee** [comment]
This seems uncontroversial because Elixir does not really favor "stacks" anyways (tuples with append, I guess?), but I am just a student. I would be happy to PR an update to this if there is mentor/maintainer consensus.

**Comment by neenjaw** [comment]
Agreed, seems like an uncontroversial change. 

@parkererl, @devonestes, or @Cohen-Carlisle (current maintainers) should be able to give you good feedback for this.

**Comment by neenjaw** [comment]
I was just looking over some of the still-active issues, and I just wanted to offer a small correction to your comment

> Elixir does not really favor "stacks" anyways

I think it would be more accurate to say that Elixir (being based on lists and no `C`-esque array or `Golang`-based slice structure) doesn't support LIFO _queues_ with lists.  But it **does** implement stacks really well if you view the head of the list as the top of the FIFO _stack_.

You are absolutely correct that tuples could be used to get around this limitation with queues, but then you have to deal with the limitation of tuples:

> A tuple may contain elements of different types, which are stored contiguously in memory. Accessing any element takes constant time, but modifying a tuple, which produces a shallow copy, takes linear time. Tuples are good for reading data while lists are better for traversals. [Elixir Docs - Tuple](https://hexdocs.pm/elixir/Tuple.html#content)

**Comment by workingjubilee** [comment]
? Queues are FIFO, stacks are LIFO, tho, aren't they?

It is true the lists can be used to implement stacks! I think I even solved a problem by doing so! Hmm, I am not sure exactly what I was thinking back then but I suspect what I meant to express is that it feels like there are a lot of other equally viable solutions in Elixir? Or maybe I was just talking nonsense. ^^;

Interesting to learn about tuples, though!
