### ISSUE TITLE
Crypto Square quiz

### ISSUE THREAD

**Issue by DukeFruitarian** [exercism/elixir#491]
Description says "For phrases that are n characters short of the perfect rectangle, pad each of the last n chunks with a single trailing space.

"imtgdvs fearwer mayoogo anouuio ntnnlvt wttddes aohghn  sseoau "(editor collapses 2 spaces in a row)

But all test checks are without spaces, for example 
``` 
test "small imperfect square" do
  assert CryptoSquare.encode("This is easy") == "tis hsy ie sa"
end
```

**Comment by neenjaw** [comment]
Hi @DukeFruitarian, 

What is your proposal? Should the description be updated? or should the test be made more specific to count for exact whitespacing?

**Comment by DukeFruitarian** [comment]
I think without spaces it looks much neat. So, may be description should be changed?

**Comment by angelikatyborska** [comment]
The exercise was fixed to use the correct (according to problems specifications) output with extra spaces: https://github.com/exercism/elixir/pull/562
