### ISSUE TITLE
Forth test

### ISSUE THREAD

**Issue by LandonSchropp** [exercism/elixir#495]
Apologies if I'm missing something obvious here. 

I noticed on [line 25](https://github.com/exercism/elixir/blob/master/exercises/forth/test/forth_test.exs#L25) of the Forth test that it expects the string `"1\x002\x013\n4\r5 6\t7"` to be split into `[ 1, 2, 3, 4, 5, 6, 7]`. The documentation for the problem says this:

> A word is a sequence of one or more letters, digits, symbols or punctuation that is not a number.

By that definition, shouldn't `5-6` parse as a word? The test as written is harder to make pass than it seems like it should be. Is the test correct, or am I missing something?

**Comment by neenjaw** [comment]
Note [line 25](https://github.com/exercism/elixir/blob/601d209027529a21614a9f8b523cc947c5f07b57/exercises/forth/test/forth_test.exs#L22) of that same file:

```elixir
    # Note the Ogham Space Mark ( ), this is a spacing character.
```

**Comment by neenjaw** [comment]
@LandonSchropp - is it okay for me to close this issue, or did you have another question?

**Comment by LandonSchropp** [comment]
Nope, that makes sense. Thanks for the clarification!
