### ISSUE TITLE
Track maintenance issues

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir#506]
With the release of @SleeplessByte's track maintenance tool, the elixir track can't make use of it just yet.

The track needs to:
- [x] Decide where problem version (against the canonical version) is recorded
- [x] Add this path to `tracks-maintenance-dashboard/src/data/tracks.json`
- [x] Ensure the regex used to parse the version in the dashboard is accurate for elixir

Are there thoughts, re: the first point?

We could record it in the mix.exs app version, and for now set the version to less than the canonical one, the as we are able to evaluate it against the canonical, change the version to match. 

We could also use a separate identifier in mix.exs or in another file, thoughts?

**Comment by devonestes** [comment]
I would argue that this version is internal to exercism and if we put in in mix.exs we’d be leaning that to learners. I would favor a separate file that isn’t included when a learner clones the exercise to their computer.

**Comment by neenjaw** [comment]
I think that's a good point.  

How do we specify what files get ignored when an exercise gets pulled? I know that the example.exs file doesn't get pulled, but where is that configured?

For the external file, is there a preferred format? JSON, YAML, etc?

**Comment by neenjaw** [comment]
Is the .meta folder ignored by the download API call?

**Comment by NobbZ** [comment]
I can't find any documentation for that, but I know that `bash` track is using it (and does not even have a label, but only the version in the `.meta/version`-file) successfully and I don't get the `.meta` downloaded when I do `bash` exercises.

**Comment by neenjaw** [comment]
It could be just like how `example.exs` isn't downloaded for this track, is that configured in this repo somewhere (try as I have, I can't find where if it is)

**Comment by NobbZ** [comment]
`config.json` does know some patterns, but I currently can't find the documentation…

Though non of the patterns does semantically fit.

We have a pattern for examples (defaults to `/[Ee]xample/` AFAIR), but the version is not part of the example, and we have a pattern for tests (which defaults to `/test/` AFAIR), but the version is not a test.

So if you do not want to put the version into student visible places, than `.meta` is the only location that makes sense in my eyes.

**Comment by neenjaw** [comment]
So then a `.meta` folder with a `version` file, where the contents is simply: `vsn x.x.x`?

**Comment by NobbZ** [comment]
Yeah, that would be possible, or as the `bash` track does it, they have a plain `.meta/version` which contains the plain version number, eg:

https://github.com/exercism/bash/blob/master/exercises/acronym/.meta/version

**Comment by neenjaw** [comment]
Ah, so that regex isn't track specific, we just have to choose one of the supported forms. 

I can agree to that form as well.

**Comment by SleeplessByte** [comment]
> For the external file, is there a preferred format? JSON, YAML, etc?

If it's just the version, I would use `exercises/{slug}/.meta/version` and it should be `text/plain` , no extension. `version` is special.

You may even choose to put it as a comment in the test file, but then it needs `v` or `version` (or `vsn`) in front of it.

> Ensure the regex used to parse the version in the dashboard is accurate for elixir

I recommend regex101.com, press JavaScript on the left. Now go to `src/hooks/useRemoteVersion.ts` and copy the regex (at ~50% of the file).

**Comment by neenjaw** [comment]
Ok, so from what I'm gathering from this, would it be acceptable to move forward with the `exercises/{slug}/.meta/verson` file, create a draft PR where the `version` for each exercise is set initially to `0.0.0`, then can evaluate each against the canonical to determine what version they are at?

I will create a draft PR, let me know if we should do this a different way.

**Comment by neenjaw** [comment]
It lives! https://tracks.exercism.io/elixir/master
