### ISSUE TITLE
Verify exercise test versions against canonical test versions

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir#510]
Now that we have implemented exercise version tracking against the canonical test versions at `exercism/problem-specifications` it is visible at [tracks.exercism.io](https://tracks.exercism.io/elixir/master/versions)

Now is a bit of a longer-term process of ensuring that our tests at least cover the test cases of the canonical versions.  In discussion with @sleeplessbyte and others, if we have test cases that are unaccounted for in the canonical that is okay -- we should try to just comment as such.

So I propose that over time (JavaScript and Typescript only do a few per week) we bring up our test cases to cover the canonical cases, then mark the exercise as the current canonical version in the `exercise/{slug}/.meta/version` file to match.

I have created a project to keep track of this progress, and to be able to call out which ones you might be working on, if unsure if it is complete, tracks.exercism.io will list unverified exercises as version `0.0.0`.

---

If there is no canonical test data version, please leave the exercise version at `0.0.0` in the case the test data is added at a later date, this will give us an easy way to identify if our test data moves out of sync with exercism/problem-specifications

**Comment by neenjaw** [comment]
#511 The first 5 exercises reviewed.

**Comment by filalex77** [comment]
Did 5 from `anagram` to `beer-song`.

**Comment by neenjaw** [comment]
Going to close this with the impending change to the problem specifications repo and the introduction of the `tests.toml` file.
