### ISSUE TITLE
queen attack open questions

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/elixir#517]
1. Should queen color matter?
2. Should the starter code allow 2 queens (e.g., 2 positional arguments for queens) or be more open ended and allow more queens (e.g., take an enumerable)?
3. If we allow more than 2, should there be special notes made that the tests only require you to handle two queens?

**Comment by neenjaw** [comment]
Thanks for opening this issue, I think this is probably a poignant time to re-evaluate a few of these problems.

I think there is there is room for either interpretation whether or not the color matters.  If we reference the [canonical test suite](https://github.com/exercism/problem-specifications/blob/master/exercises/queen-attack/canonical-data.json) the test cases themselves references the color of the queens being tested.  I don't know if this was done out of being descriptive for the test suite or if the intention is to have queen colors explicitly stated in the struct.

In the [source material](http://users.csc.calpoly.edu/~jdalbey/103/Projects/ProgrammingPractice.html), queen color is not discussed and this is a reduction of the n-queens problem. 

I believe at this point the problem specifications are frozen, so I'm not sure we can ask for a change there, but I think we could embrace the spirit of the problem more by ignoring queen color and just looking at a coordinate pairs.

I am also in favor of dropping the to_string output of the problem, as there are lots of problems in the problem set which look at this.

**Comment by angelikatyborska** [comment]
Refreshing an old issue 🙂

I personally like this exercise as it is and wouldn't change it. It's up to date with problem specifications and implements some extra details that the problem specification suggest can be implemented (checking the two queens are not on the same position, printing the board). They don't suggest anything about allowing for more than 2 queens. I'm a sucker for sticking to The Rules ™️, so I wouldn't deviate from problem specifications without a good, Elixir-specific reason. Less deviation = less thinking necessary = easier to maintain the track.

**Comment by angelikatyborska** [comment]
There hasn't been a contrary response to my opinion for over a year, so I am going to assume this discussion is dead and close the issue.
