### ISSUE TITLE
Recruiting additional maintainers for Elixir

### ISSUE THREAD

**Issue by kytrinyx** [exercism/elixir#524]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by nathanchere** [comment]
I would be happy to help with this. Exercism helped a lot with taking my Elixir understanding out of the clumsy novice stage. I have completed the entire Elixir track as a student myself, have mentored on that track since I felt confident enough to have something to contribute (when @chriseyre2000 hasn't already burned through the entire mentoring queue :smile:) and would welcome the opportunity to improve the Exercism experience for other students. My exercism handle is the same as here `nathanchere`

**Comment by filalex77** [comment]
I am an Elixir (and not only) mentor on Exercism (though I'm not as active as I was used to), and I very much enjoy the process. I haven't had the possibility to contribute much to this repository, but I would be glad to. I'm `BrightOne` on Exercism :)

**Comment by neenjaw** [comment]
Yep, I'm totally still on board for v3. I have also had positive encounters with both @filalex77 (esp with his helpful PRs in Sept/Oct) and @nathanchere  on exercism and think they would be nice to bring them in.

**Comment by devonestes** [comment]
I'm still in. I can't do 2/3 hours/week, but I can do 6 hours/month (all on one day a month).

**Comment by chriseyre2000** [comment]
I can see if I can help where I can. I can't guarantee a fix amount of time per week.

**Comment by Cohen-Carlisle** [comment]
:wave: I'm still here and can do 2-3 hours a week.

**Comment by fireproofsocks** [comment]
I'd like to help out if I can.

**Comment by kevgathuku** [comment]
Hello 👋 
I'm Kevin ([@kevgathuku](https://exercism.io/profiles/kevgathuku) on exercism) and I would like to help out with the Elixir track. I've been intrigued by Elixir and I would like to use this chance to learn more about the language and to collaborate with other talented folks here.

**Comment by ryoheiw** [comment]
Hello, I might be late to this thread but I'd like to help out as well with the Elixir track. @ryoheiw on exercism. Exercism was a great help to me when I was getting into the industry and I landed my first role job because of it. Let me know if I can be of any help!

**Comment by angelikatyborska** [comment]
@ryoheiw It's never too late, there's always enough work for everybody that wants to help 🙂.

I would strongly recommend that you start helping out by becoming a mentor (https://exercism.io/become-a-mentor). There's always enough solutions in the mentoring queue. Having some experience as a mentor is very important to understanding how Exercism works and it will help you make more meaningful contributions to the track. If you don't like it, you can always stop doing it with no consequences 😉 

When you sign up as a mentor, you get an invite to a Slack workspace where mentors and maintainers hang out, help one another, discuss tasks etc.

If you want to jump right into coding, this is a general overview of the types of tasks that we need help with: https://github.com/exercism/elixir/blob/main/HELLO.md

At the moment, there are a few good first issues of type `4. Create an analyzer for an existing practice exercise`. You can find them here: https://github.com/exercism/elixir-analyzer/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

As a general rule, don't hesitate to ask if you have questions. You can tag myself and/or @neenjaw in them. Feel free to open draft PRs to ask for feedback early. Most of the documentation that you need, you should be able to find in this repository, in https://github.com/exercism/elixir-analyzer and in https://github.com/exercism/docs

**Comment by ryoheiw** [comment]
@angelikatyborska Amazing 👍  Thank you for all the resources and direction. Looking forward to diving in!
