### ISSUE TITLE
The very first exercises of the track are way more difficult than others later on.

### ISSUE THREAD

**Issue by ryanzidago** [exercism/elixir#534]
Hi everyone,

first, thanks for Exercism!
I'm currently going through the Elixir track and noted some discrepancies regarding the difficulty of some of the exercises. I know this issue has been [mentioned in the past](https://github.com/exercism/elixir/issues/190), but I still think it is relevant today.

I would rather move **Flatten Array**, **Triangle** and **Accumulate** and eventually **Scrabble** at the very beginning of the track. I know that difficulty is subjective, but those exercises requires very little knowledge of Elixir/functional programming. Another example: the **Isogram** exercism is way simpler than the **Protein Translation** problem.

I actually found the very firsts additional exercises pretty complex in comparison to later exercises down the track. It might intimidate some, which I do not think is what Exercism want.

**Comment by neenjaw** [comment]
Hey Ryan,

I think you are describing the very real problem with all track's in version two. The exercises just aren't super good at teaching elixir. 

Which is why we are working on v3!

Check out this video: https://youtu.be/5Cj1Dr9m3GM

It seems to echo what you've written above, no?

**Comment by ryanzidago** [comment]
Hey @neenjaw, 

Thanks for the quick reply.

I didn't know that Exercism is preparing a whole new version of its website! Maybe I should go slowly on the Elixir track until V3 is released so that I get to enjoy it too!

Since it seems that V3 will definitely address the point that I mentioned above, then I'll close the issue!

**Comment by neenjaw** [comment]
Ya, I don't think there is a concrete release date set, but I have heard roughly in Q3 hopefully. 

S
Have you worked through elixir-lang's getting started guide and the elixir school content? They are certainly less exercises and less mentorship, but they will give you the tools and constructs to approach most of the problems on the track.

And if you ever do take on a problem and which you get stuck in, please just submit something (pseudo code approach, or non-working code that shows your thoughts) and open a discussion and dialogue. 

I think most of the mentors have an excitement about mentoring/coding in general and just like to grok these things together.
