### ISSUE TITLE
Add mix-test.watch to all mix.exs dependencies

### ISSUE THREAD

**Issue by cdimitroulas** [exercism/elixir#552]
Hi there,

I would like to suggest that we add `mix-test.watch` as a dependency for all exercises so that the unit tests can be easily ran in "watch mode". This greatly improves the ergonomics of working on the exercises as it avoids the developer from having to manually run `mix test` after every change.

I know a lot of work is going into Exercism v3 at the moment so I'm happy to pick up this work if the maintainers agree that this is a good idea :smile:

**Comment by neenjaw** [comment]
Up to this point we've kept mix projects as close to the generated default just to keep things as simple as possible. The exception to this is that we have commented out the language version requirement to facilitate people working off of distro versions that may not be current. 

But it also serves us in that we don't have to go in and handle updating mix.exs for each version. 

Questions I would have before going forward:

 - Is `mix-test.watch` the only lib that accomplishes this? Or are there alternatives?
- how stable is the version of `mix-test.watch`, will it require us to bump the version often?
- Does `mix-test.watch` require a specific elixir version? We are trying to support >= 1.6 at this time. 
- What deps does `mix-test.watch` pull in with it?

@angelikatyborska, @Cohen-Carlisle: your thoughts?

**Comment by angelikatyborska** [comment]
Watching files to automatically re-run the test suite is not a standard practice in the Elixir community and rather a matter of personal preference, and as such, in my opinion, it doesn't belong in the project configuration given to every Elixir student on this platform.

Like @neenjaw said, we are trying to keep the projects as close to defaults as possible to make them accessible to a bigger audience, including not specifying language version requirements. Allowing people to use any Elixir version that they might have installed doesn't go well with external dependencies. Those tend to need updating when a new language version comes out and might not even be backwards-compatible.

A beginner would most likely not even realize that an alternative way of running tests is available. A seasoned Elixir developer will know how to add the dependency to an exercise in case they want to use it.

**Comment by cdimitroulas** [comment]
Thanks for your comments. Sounds like my suggestion isn't a good fit for the way exercism works. In particular this concern makes me think it's not worth doing:

>Allowing people to use any Elixir version that they might have installed doesn't go well with external dependencies. Those tend to need updating when a new language version comes out and might not even be backwards-compatible.

To be honest, as someone who is used to using a TDD workflow I was surprised that `mix test` doesn't have a built-in way to run tests in a "watch mode". Perhaps something for me to try and convince the `mix` maintainers to add  :stuck_out_tongue_closed_eyes:
