### ISSUE TITLE
poker: tests are hard to pass with strict order

### ISSUE THREAD

**Issue by MeerKatDev** [exercism/elixir#554]
I just did the Poker exercise, and one main point of my strategy was to sort the cards from 1 to A just after the input ([my solution](https://exercism.io/tracks/elixir/exercises/poker/solutions/acc983b5aed14ff9a5521c3c0e2b4445)). When I was trying to pass the tests, it hit me that I had a lot of tests not passing because they are checking on direct equality between two lists, i.e.:
```
Poker.best_hand(hand) == ~(4H 3S 5S 6S AH)
```
which checks that the returned hand is exactly in the order in which the cards were dealt. 

I think this is really confusing, since in Poker the order with which you get the cards don't matter (to my knowledge), and moreover it's written nowhere in the exercise that the cards need to be in the same order as they were given in the input, which I think would also add a unnecessary complication to the exercise.

I saw that the Allergies exercise has a utility in its tests that checks for equality of a set, not of a list, which would suit this case well already, so I'd propose to change the tests in Poker to follow that example.

**Comment by neenjaw** [comment]
I'd like to hear from other maintainers what their experience has been of this problem, but I have been thinking about this since you brought it up yesterday in slack. 

If you have time to create a PR, adding a wait to compare the hands so that the order doesn't matter (like the allergies exercise), I am open to it and would probably have time to review it. 

If you can include and estimate of how much work it is and how much it would take to maintain, that would be nice.

**Comment by MeerKatDev** [comment]
I think 30 minutes top, it's only about changing the `==` operators, I suppose.
It would be good to create a note somewhere that there is such a comparison method in some exercises (maybe Allergies is not the only one?), so that we would be able to maintain them together in case of changes.

I'm not sure what you mean by 

> how much it would take to maintain

 , but I suppose that changes would happen when something in the Elixir API will change. I think it's a remote possibility, in this case, so not much work.

**Comment by neenjaw** [comment]
I think I mean that everything has a maintenance cost, but I think you're right in this case once the comparator works, there is probably little maintenance required.
