### ISSUE TITLE
[v3] Replace concept exercise for `streams` - `mensch-aergere-dich-nicht`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir#561]
The exercise `mensch-aergere-dich-nicht` was written initially to teach `pipe-operator`, `randomness` and `streams`, but it's not very good at any of that. Since then, `captains-log` was written to teach about `erlang-libraries` and `randomness`, and `pipe-operator` was moved earlier into the tree, to the `high-school-sweetheart` exercise. The part of `mensch-aergere-dich-nicht` that uses streams relies on a not very popular Stream function `Stream.transform/3` that's not very easy to use. It feels more like a riddle than a concept exercise. When I attempted to solve it without looking at the solution, I wasn't really sure how, and concept exercises are supposed to be easy for seasoned Elixir developers.

For this reason, we should scrap this exercise altogether and replace it with something better.

**Comment by neenjaw** [comment]
exercise now replaced by lucas numbers
