### ISSUE TITLE
Create `introduction.md.tpl` files for concept exercises

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir#686]
According to https://github.com/exercism/docs/blob/main/building/configlet/generating-documents.md#document-concept-exercises-introductionmd-file, it will be possible to use configlet to generate concept exercise `introduction.md` from its concepts' `introduction.md` by creating a `<concept-exercise>/.docs/introduction.md.tpl` file.

All of Elixir concept exercise introductions are exact copies of their concepts' introductions, so we should leverage that template file instead of maintaining two identical copies.

Let's do this once configlet supports this feature.

Note there might be a few exceptions where we do want a slightly different introductions, e.g. for `freelancer-rates` (`integers` and `floating-point-numbers`)

**Comment by angelikatyborska** [comment]
Configlet currently supports templates, but not changing heading levels when merging templates.

**Comment by jiegillet** [comment]
We don't need that feature, do we? Our introductions are identical.

**Comment by angelikatyborska** [comment]
We do. Our exercise introductions have headings one level lower than concept introductions because we add concept names as h2. For example:
```
<!-- bitstrings introduction.md >
# Introduction

Bitstrings are ...

## Pattern matching

Pattern matching on bitstrings ...
```
and
```
<!-- tail call recursion introduction.md >
# Introduction

When recursing ...
```
becomes
```
<!-- file sniffer introduction.md >
# Introduction

## Bitstrings

Bitstrings are ...

### Pattern matching

Pattern matching on bitstrings ...

## Tail Call Recursion

When recursing ...
```

**Comment by angelikatyborska** [comment]
To be clear, we're waiting on: https://github.com/exercism/configlet/issues/328
