### ISSUE TITLE
Mix command not found

### ISSUE THREAD

**Issue by sunkam96** [exercism/elixir#698]
Hello, 

I'm super new to elixir but it seems like the Mix build tool should come with installing exercism. However, after I install (I tried via brew and manually) exercism successfully, it still seems that Mix is not there. 

`% mix test
zsh: command not found: mix`

**Comment by neenjaw** [comment]
Hello, you need to install elixir for your machine.  There are good instructions at the Elixir-lang official page found here: https://elixir-lang.org/install.html

**Comment by angelikatyborska** [comment]
A good place to look for help in case you have problems installing Elixir is this Gitter channel: https://gitter.im/exercism/xerlang A few Exercism volunteers that know Elixir and Erlang well monitor this channel and try to help people. If you don't get an answer there, try the general Exercism support channel: https://gitter.im/exercism/support
