### ISSUE TITLE
Markdown exercise already answered

### ISSUE THREAD

**Issue by ThiagosLima** [exercism/elixir#770]
Hi! I have not done the Markdown exercise yet. Today I download it but it was already answered.

**Comment by neenjaw** [comment]
Markdown is a different type of exercise.  In the state you downloaded, it is written badly.  The point of Markdown is to refactor and correct it, while maintaining all of the tests to still pass.

**Comment by ThiagosLima** [comment]
You are right @neenjaw! Sorry :sweat_smile:

I was making some exercises like TDD. So run the tests and fix the code. I will pay more attention to the instructions :blush:

**Comment by neenjaw** [comment]
No problem! That exercise is kind of the exception, so it can be tricky to shift modes. :D
