### ISSUE TITLE
Concept exercise `language-list`: idiomatic solution gives confusing error message

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir#813]
If I know Elixir a bit already and use pattern matching instead of `hd` and `tl`, the tests fail with error messages that do not really tell me what I did wrong. See screenshot.

![Screen Shot 2021-07-04 at 09 50 10](https://user-images.githubusercontent.com/7852553/124377675-6d87c780-dcad-11eb-889e-40f54c853f46.png)

**Comment by neenjaw** [comment]
Personally, i don't think this is a bug. And I think the error "FunctionClauseError (...)" is explaining what is going on.  However, I hear that you are saying that you'd like it to explain what is wrong more clearly. Open to your suggestions here.

**Comment by jiegillet** [comment]
I also don't really think this is a bug. If you want to implement something with pattern matching you should always consider all possible cases, this is no exception. 
I also recognize that it is a bit abstract to differentiate between the two errors., maybe giving an extra hint somewhere.

**Comment by angelikatyborska** [comment]
I think my problem here is that the instructions do not specify what should happen in `remove` and `first` for an empty list. But we cannot really specify without revealing how to implement it.

If we say "it should raise ArgumentError", we're touching on a subject of errors and raising, that's not yet known in this exercise. Some people might also think they need to raise that error explicitly and will try to write `if list == [], do: raise ArgumentError`.

If we say "it should do with an empty list whatever tl/hd does with an empty list", we're revealing the solution 😞.


My proposal would be this:
1. Remove the two test cases that check what happens for empty lists
2. Add an analyzer check that will return comments of type `informative` (as opposed to our usual `essential` comments) that will tell the student that they can also use `tl/hd` if they didn't

**Comment by angelikatyborska** [comment]
I just realized that there's a yet another option that's idiomatic and doesn't even go outside the taught concept that fails the same tests: `List.first` instead of `hd` and `List.delete_at` instead of `tl`:

![Screen Shot 2021-07-10 at 09 32 41](https://user-images.githubusercontent.com/7852553/125155691-e8475b80-e161-11eb-8acd-daec533e804c.png)
