### ISSUE TITLE
Every concept exercise has a test warning "module attribute @task_id was set but never used"

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir#818]
We added task ids to test cases by introducing a custom module attribute. Because this attribute is not consumed from within the same file, there is a warning:
```
warning: module attribute @task_id was set but never used
  test/rules_test.exs:66
```

The warning will be visible to all students using the CLI when then run `mix test`. This might be confusing and/or annoying to some students.

Is there a way to tell Elixir to chill out and allow this module attribute? Or would we replace it with `@tag task_id: 1` instead?

**Comment by jiegillet** [comment]
I looked into it a bit, it seems that disabling warning is not the Elixir way (which I tend to like).

> Or would we replace it with `@tag task_id: 1` instead?

Seems to me to fit right into what tags are for :)

**Comment by angelikatyborska** [comment]
Alright. That would mean a boring search and replace in this repository, and some more interesting coding in the test runner. Here's the PR that added the initial functionality: https://github.com/exercism/elixir-test-runner/commit/b95f66e0042b05cd9157acfecccfd69b61b986de That should provide some idea what needs changing
