### ISSUE TITLE
Concept exercise stubs raise errors but errors are taught later on 

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir#819]
Concept exercise stubs raise errors but errors are taught later on. Students might get confused about the `raise` keyword and how can you raise a string :) but that's not the point of the exercises they're solving.

A partial example of a current solution stub for `recursion` (comes before `errors`):
```elixir
defmodule BirdCount do
  def today(list) do
    raise "Please implement the today/1 function"
  end

  def increment_day_count(list) do
    raise "Please implement the increment_day_count/1 function"
  end
end
```

What should we do instead?

- comments?
    ```elixir
    defmodule BirdCount do
      def today(list) do
        # Please implement the today/1 function
      end

      def increment_day_count(list) do
        # Please implement the increment_day_count/1 function
      end
    end
    ```
- nothing?
    ```elixir
    defmodule BirdCount do
      def today(list) do
      end

      def increment_day_count(list) do
      end
    end
    ```

**Comment by jiegillet** [comment]
My vote goes to "nothing". When solving exercises it always feels like extra work to me to delete the comments. Of course I know I'm supposed to implement the function!

**Comment by angelikatyborska** [comment]
Maybe I misunderstood Jeremy's worry and it was only about the `hello-world` exercise because Ruby stubs raise a `NotImplemented` error and he wants it like that 🤔 
https://github.com/exercism/ruby/blob/main/exercises/concept/lasagna/lasagna.rb#L2-L4

Python stubs are empty functions:
https://github.com/exercism/python/blob/main/exercises/concept/log-levels/enums.py#L8-L9

JavaScript stubs raise errors:
https://github.com/exercism/javascript/blob/main/exercises/concept/freelancer-rates/freelancer-rates.js#L29

C# stubs raise errors:
https://github.com/exercism/csharp/blob/main/exercises/concept/elons-toys/ElonsToys.cs#L7

I think the question is what is clearer to the student
1. raising an error
   - a bit harsh
   - maybe confusing because errors aren't known yet
   - unidiomatic in Elixir
   - there's no specific `NotImplemented` error like Ruby and C# have
   - but provides a clear message what to do
2. empty function
   - friendlier test failure
   - maybe confusing at first if the student didn't internalize yet that there's always an implicit return
   - but that's idiomatic
   - no clear instruction what to do (if we don't include comments)
       - Jeremy says that if we have empty functions, we should add comments "please implement..." but I totally agree that it's annoying having to remove them everywhere 😅 

Here's a comparison of the first test failure, raising an error vs implicit nil return (but in Ruby because there's currently a bug on exercism.lol that is blocking me from accessing the Elixir track)


![Screen Shot 2021-07-07 at 07 13 54](https://user-images.githubusercontent.com/7852553/124704836-03f9fa00-def5-11eb-846e-c78971df5d5a.png)


![Screen Shot 2021-07-07 at 07 14 22](https://user-images.githubusercontent.com/7852553/124704824-fe041900-def4-11eb-8d55-6a1caeff05bb.png)

**Comment by neenjaw** [comment]
I think sometimes we forget that the prototypical student knows what basic programming is. There will be outliers (on both sides), so I don't think we should be too worried about this.  I don't think any of these options are more or less right or wrong, but I'm okay  if you want to remove the `raise` in favour of a comment.
