### ISSUE TITLE
Reorder practice exercises

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir#821]
The order of exercises in `config.json` matters. It's used to display them on the website.

If you're completely new to the track, you will first see all concept exercises in their order in `config.json`, and then all practice exercises. If you started working on the track already, this ordering still applies (type, difficulty), but within the same status (in progress, completed, unlocked, locked).

Our current order of exercises is a bit... historical. First, we have former core exercises in their order from v2:
- rna transcription
- word count
- roman numerals
- bob
- beer song
- robot simulator
- list ops
- markdown
- bank account
- zipper
- bowling
- forth
- 
From very easy to very hard. And then you randomly go back to very easy (resistor color, two fer), and then I'm not sure what's the order... probably they're ordered by which core exercise unlocked them in v2. At the very end, we have a bunch of new exercises added after we stopped synchronizing with v2.

I would like to propose that we clean up the order so that all practice exercises are always ordered by their difficulty, and within the same difficulty either alphabetically or by how many prerequisites they have? Or hand-picked order however we want 🙂 ?

Alphabetically would be easier. This would produce the order:

- hello-world (exception to the rune, always first)
- resistor color
- simple linked list
- two fer
- accumulate
- acronym
- all your base
- anagram
- armstrong numbers
- ...
- forth

Upsides:
- easy to find most challenging exercises
- guiding students to the easiest ones first
- better than current random-ish order

Downsides:
- resistor color family would be separated 😢 
- the exact number for difficulty becomes more important, but maybe we didn't choose it so carefully?
- exercise position will change if it ever gets easier or more difficult

If we do this, an automated check on the CI for this ordering rule would be great to have.

**Comment by neenjaw** [comment]
Could write a bash script to just sort the config by name and difficulty using `jq`: https://phpfog.com/sorting-json-by-value-with-jq/

**Comment by angelikatyborska** [comment]
Yeah, it would be easy to automate the sorting. The most difficult part would probably be getting it nicely formatted in the end.
