### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/elixir#850]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total..........751
✅ Successful.....744
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........7

Errors in ./reference/exercise-concepts/bank-account.md
<span style="color:#ff5555">✗ https://exercism.io/tracks/elixir/exercises/bank-account/solutions/961596ab0cce445aa918452137feae1b (HTTP status client error (404 Not Found) for url (https://exercism.io/tracks/elixir/exercises/bank-account/solutions/961596ab0cce445aa918452137feae1b))</span>

Errors in ./docs/TESTS.md
<span style="color:#ff5555">✗ http://elixir-lang.org/docs/stable/elixir/typespecs.html (HTTP status client error (404 Not Found) for url (https://elixir-lang.org/docs/stable/elixir/typespecs.html))</span>

Errors in ./HELLO.md
<span style="color:#ff5555">✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir+repo%3Aexercism%2Felixir-test-runner+repo%3Aexercism%2Felixir-representer+repo%3Aexercism%2Felixir-analyzer (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir+repo%3Aexercism%2Felixir-test-runner+repo%3Aexercism%2Felixir-representer+repo%3Aexercism%2Felixir-analyzer))</span>
<span style="color:#ff5555">✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-representer (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-representer))</span>
<span style="color:#ff5555">✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir))</span>
<span style="color:#ff5555">✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-analyzer (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-analyzer))</span>
<span style="color:#ff5555">✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-test-runner (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-test-runner))</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by angelikatyborska** [comment]
There's a PR already for this: https://github.com/exercism/elixir/pull/845 but it doesn't fix that one broken link, I'll look into it

**Comment by angelikatyborska** [comment]
@ErikSchierboom I think your link checker got some false positives here:
```
Errors in ./HELLO.md
✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir+repo%3Aexercism%2Felixir-test-runner+repo%3Aexercism%2Felixir-representer+repo%3Aexercism%2Felixir-analyzer (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir+repo%3Aexercism%2Felixir-test-runner+repo%3Aexercism%2Felixir-representer+repo%3Aexercism%2Felixir-analyzer))
✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-representer (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-representer))
✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir))
✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-analyzer (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-analyzer))
✗ https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-test-runner (HTTP status client error (404 Not Found) for url (https://github.com/pulls?q=is%3Aopen+repo%3Aexercism%2Felixir-test-runner))
```
