### ISSUE TITLE
Wrong link in About section in repository

### ISSUE THREAD

**Issue by michallepicki** [exercism/elixir#859]
Currently the link is https://exercism.io/languages/elixir 
A working link is https://exercism.org/tracks/elixir

Not sure if it's worth bubbling up to the v3 website repo? There may be lots of io/languages/xx links floating around the internet, maybe a redirect could be added to keep them working

**Comment by angelikatyborska** [comment]
I'll fix the `.io` -> `.org` now. But where do you see `/languages` instead of `/tracks`? I can't find it.

**Comment by michallepicki** [comment]
I mean this section of this repository:
![image](https://user-images.githubusercontent.com/4972756/131725138-d1d9aff9-88c0-4f6f-84e2-8c7d6bab3933.png)

**Comment by angelikatyborska** [comment]
😂 can't grep for the repository description in my IDE

**Comment by angelikatyborska** [comment]
I created an issue for the whole organization because that's a global problem that wasn't mentioned yet: https://github.com/exercism/exercism/issues/5623

As for the links in this repo, we were already told to update them and I forgot 😇
