### ISSUE TITLE
IO.inspect working in few exercises only

### ISSUE THREAD

**Issue by mpas97** [exercism/elixir#876]
In my journey through Elixir I have realized that things like IO.inpect() are mostly not working, although each exercise mentions it clearly in the "how to debug" section. And not being able to debug things, especially when learning a new language, is very hard.

One of the few exercises where it works:
<img width="956" alt="grafik" src="https://user-images.githubusercontent.com/9994218/132104679-37a3f46d-b2f9-403c-95df-64f7b81825b5.png">
One of the many where it doesn't:
<img width="1262" alt="grafik" src="https://user-images.githubusercontent.com/9994218/132104924-509e127c-2c8f-4b38-a225-5e6a6eb6dd99.png">

**Comment by angelikatyborska** [comment]
Thank you! This bug has already been reported here: https://github.com/exercism/elixir-test-runner/issues/55

I will close this because it's a duplicate but we will of course try to fix this soon.

**Comment by mpas97** [comment]
Thanks, I only searched this repo for any already existing issues. 😬
