### ISSUE TITLE
Simple Linked List - Test at line 100

### ISSUE THREAD

**Issue by czrpb** [exercism/elixir#900]
Hi!

I believe this test is slightly wrong:

https://github.com/exercism/elixir/blob/67824de8209ff1b6ed2f736deedfb5bd815130ca/exercises/practice/simple-linked-list/test/linked_list_test.exs#L100

I believe the expected `pop`s are in the wrong order. You can also reference other tests where the expectations are LIFO; such as tests on lines: 53 & 81.

I have the code locally and can do a PR, but it will be my first and thus want to adhere to community norms/mores.

Thoughts? Suggestions?

Thanks!!

  << q

**Comment by czrpb** [comment]
Hi again!

I have forked and can do a PR if appropriate and whenever! :)

thx!! << q

**Comment by jiegillet** [comment]
Hi @czrpb,
Thank you for raising this issue.
Yes, please, open a PR and we will gladly review it!

**Comment by czrpb** [comment]
Hi!

Ok, I will:

1 Close the current PR (which is changing the test)
2 Open a PR to change the documentation for practice exercise

Hope I am not wasting your time!??

thx!! << q

**Comment by jiegillet** [comment]
No time wasted whatsoever, thank you for your help!
But there is no need change the documentation, just the name of the test will be enough.

**Comment by czrpb** [comment]
Hi!

New PR #908 that:
* Updates 2 test names reminding that order should be kept/preserved
* 1 new test that verifies that `from_list/1` is successive `push/2` but reversed

Thx!

**Comment by jiegillet** [comment]
Closed via #908.
