### ISSUE TITLE
Typo in test definitions for `Guessing Game`

### ISSUE THREAD

**Issue by devtayls** [exercism/elixir#903]
Tests 4 & 5 include an erroneous '7' in their description.

`test so close when guess differs from 7 secret by -1 (GuessingGameTest)` -> `test so close when guess differs from secret by -1 (GuessingGameTest)`

Where the assertion is `assert GuessingGame.compare(64, 63) == "So close"`

`test so close when guess differs from 7 secret by +1 (GuessingGameTest)` -> `test so close when guess differs from secret by +1 (GuessingGameTest)`

Where the assertion is: `assert GuessingGame.compare(52, 53) == "So close"`

**Comment by angelikatyborska** [comment]
You're right! Would you want to open a PR with that change?

**Comment by devtayls** [comment]
Already on it

**Comment by devtayls** [comment]
https://github.com/exercism/elixir/pull/904
