### ISSUE TITLE
Mention other potentially useful test runner options in `exercises/shared/.docs/tests.md`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir#906]
Extend `exercises/shared/.docs/tests.md` with the mention of those useful flags:

- To run tests in order: `--seed 0`
- To run tests until the first failure: `--max-failures 1`
- To run a single specific test: `test/some/particular/file_test.exs:12`
- anything else?

Also we need to fix the text about pending test to explain that only practice exercises have pending test.

**Comment by jiegillet** [comment]
Maybe `--listen-om-stdin` too? I use it a lot.

And definitely add a link to[https://hexdocs.pm/mix/1.12/Mix.Tasks.Test.html#module-command-line-options]( https://hexdocs.pm/mix/1.12/Mix.Tasks.Test.html#module-command-line-options) for more options.

**Comment by czrpb** [comment]
Hi!

I am happy to work on this if acceptable?

thx!!

**Comment by jiegillet** [comment]
Of course, please give it a go!

**Comment by angelikatyborska** [comment]
@czrpb How is it going? Do you need any help with this task?

**Comment by czrpb** [comment]
hi!

arrg! tl;dr -> swamped w/ the "real" world (which sucks!).

will do a PR ASAP to give an idea of what im thinking.

sorry, and of course feel free to kick me off! :wink: 

<< q

**Comment by angelikatyborska** [comment]
No worries, this is not urgent 🙂 I just wanted to see if there are any blockers.

**Comment by czrpb** [comment]
Made a draft PR for comments!

tagging @angelikatyborska  / @jiegillet as draft PRs dont notify correct?
