### ISSUE TITLE
Extend `remote-control-car` tests

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir#910]
There are those existing checks for functions that accept the struct:
```elixir
  test "display distance raises error when not given struct" do
    fake_car = %{
      battery_percentage: 100,
      distance_driven_in_meters: 0,
      nickname: "Fake"
    }

    assert_raise(FunctionClauseError, fn ->
      RemoteControlCar.display_distance(fake_car)
    end)
  end
```

Those checks guard against plain maps, but not against other structs. It's possible to do a pattern match on `%{__struct__: _}` that will allow *any* struct.

To prevent this, we could add extra tests (`"... raises error when given an unexpected struct"`?) that attempt to pass a locally defined `FakeRemoteControlCar` struct and check that `FunctionClauseError` is raised.

**Comment by Stqs** [comment]
I can take it @angelikatyborska 
Do you allow creating of a new branches in this repo?

**Comment by angelikatyborska** [comment]
@Stqs Thank you for the help 🙏. Unfortunately creating a branch in this repository is a privilege that requires write access, which is reserved for maintainers. The standard procedure in all open source repos on GitHub is that contributors must create their own fork first (like you have done already).
