### ISSUE TITLE
Error in test case for Bird Count

### ISSUE THREAD

**Issue by tradfursten** [exercism/elixir#925]
Isn't the final test in the bird count exercise wrong.

The function should return the index of the largest element but the test asserts the following:
```
assert BirdCount.busy_days([0, 6, 10, 4, 4, 5, 0]) == 3
```
The third element in the list has index 2.

**Comment by angelikatyborska** [comment]
The function doesn't return indices. It returns how many days have at least 5 birds visiting. In this case 3 - `6`, `10`, and `5`. The test is correct.

**Comment by tradfursten** [comment]
You should read the whole instructions before you say anything :)
