### ISSUE TITLE
Instructions in list-ops doesn't match the expected function signature

### ISSUE THREAD

**Issue by kahgoh** [exercism/elixir#937]
While working on the list-ops exercise, I noticed the some of the methods in the instructions doesn't match what is expected by the tests. For example:
- The instructions list a `concatenate` function, but the tests expect `concat`.
- The instructions lists the `list` as the second argument to the functions, but the tests expects it as the first.

**Comment by jiegillet** [comment]
Well the instructions also say before the list of functions "The precise number and names of the operations to be implemented will be track dependent to avoid conflicts with existing names" and that is exactly what is happening here.

The names of functions and order of the arguments have been chosen to match the Elixir built-in function (but sometimes renamed to avoid name clashes).

**Comment by jiegillet** [comment]
Closing the issue. See more details on #938.
