### ISSUE TITLE
Redirecting to Page Not Found in Elixir School

### ISSUE THREAD

**Issue by ThiagoPMaceda** [exercism/elixir#948]
While I was reading through the basics on Elixir(https://exercism.org/tracks/elixir/concepts/basics) I noticed that clicking in the pattern match symbol "=" link was redirecting to a page not found in Elixir School, that is happening because the link was changed (probably with the recent update of Elixir School). Below is the link that I was clicking.
![image](https://user-images.githubusercontent.com/30845442/135859833-3f7c6741-8a78-4ab2-8803-11bc20ee807c.png)

**Comment by jiegillet** [comment]
Looks like the `pattern-matching` in the URL should be `pattern_matching`.

**Comment by jiegillet** [comment]
Closed via #953.
