### ISSUE TITLE
`high-score` requires task 5 function beeing implemented for task 4 test

### ISSUE THREAD

**Issue by NobbZ** [exercism/elixir#960]
Currently there is a test which fails despite the fact, that *so far* all tasks have been properly implemented, as the test also uses a function that has to be defined in task 5.

https://github.com/exercism/elixir/blob/340b67ea603f47f9324f738e494ac62f73b0b159/exercises/concept/high-score/test/high_score_test.exs#L103-L113

This test should not use `HighScore.update_score/2`, but instead give a score value when calling `HighScore.add_player/3`.

**Comment by jiegillet** [comment]
Agreed. 
Care to submit a PR? :)

**Comment by kotp** [comment]
@jlirochon Absolutely.  Make a PR and mention this issue, so that it can be marked claimed by you!
