### ISSUE TITLE
Secrets exercise 4 - "Create a divider" showing incorrect example?

### ISSUE THREAD

**Issue by Pistrie** [exercism/elixir#992]
https://github.com/exercism/elixir/blob/main/exercises/concept/secrets/.docs/instructions.md

Maybe I'm looking at this completely the wrong way, but shouldn't the result in this example be 10.666666etc? To get 10 the divider.(param) should be 30, no?

**Comment by angelikatyborska** [comment]
See the comment below the code example:

> Make use of integer division.

**Comment by Pistrie** [comment]
omg why didn't I see that 😅
